### ISSUE TITLE
change monolog/monolog requirement

### ISSUE THREAD

**Issue by mwansinck** [Adyen/adyen-php-api-library#1]
Please make the monolog/monolog version less restrictive,

`"monolog/monolog": "1.16.0"`

to

`"monolog/monolog": "~1.16"`

**Comment by rikterbeek** [comment]
Hi Marco,

Yes something we can do. We will change this in the next release

Regards,
Rik
Adyen

**Comment by mwansinck** [comment]
Thanks :+1:

**Comment by rikterbeek** [comment]
Hi @mwansinck,

This is now included in our release version 1.0.1.

Regards,
Rik
Adyen
