### ISSUE TITLE
reserved name for php 7 : Resource

### ISSUE THREAD

**Issue by Grummfy** [Adyen/adyen-php-api-library#10]
The class called "Adyen\Service\Resource" is reserved in php 7. You should change the name of it

**Comment by rikterbeek** [comment]
Hi @Grummfy,

Yes it is we will change this reserve name to ResourceModel.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Done forgot to commit it against this issue. You can see code changes here: 509e45b6d17552dfe1e03e2c73c5b6370a754337

**Comment by Grummfy** [comment]
when the next release will be plannified?
