### ISSUE TITLE
Internal server error 500 using Boleto as payment method

### ISSUE THREAD

**Issue by nrsWebs** [Adyen/adyen-php-api-library#102]
**PHP version**: 7.2.13
**Library version**: 1.6.0
**Environment**: Using Docker for windows
**Magento version**: 2.3.0
**Description**

When I use boleto bancario as payment method the request response is:

AdyenLoggerTest.INFO: JSON Response is: {"status":500,"errorCode":"000","message":"HTTP Status Response - Internal server error","errorType":"internal"} {"is_exception":false} []
AdyenLoggerTest.ERROR: 000: HTTP Status Response - Internal server error {"is_exception":false} []

This error only appear inthis payment method, whe I use HPP the payment are processed correctly.

I'm debugging and I find that the error in the response is in this file:

<magento_base_dir>\src\vendor\adyen\php-api-library\src\Adyen\HttpClient\CurlClient.php

On the line 84:

list($result, $httpStatus) = $this->curlRequest($ch);

FYI
<pre>
AdyenLoggerTest.INFO: Request url to Adyen: https://pal-test.adyen.com/pal/servlet/Payment/v40/authorise {"is_exception":false} []
AdyenLoggerTest.INFO: JSON Request to Adyen:
{
	"merchantAccount":"*****************",
	"shopperReference":"5",
	"shopperEmail":"*****@*******",
	"shopperIP":"******",
	"billingAddress":{
		"street":"Roque Petroni Jr",
		"postalCode":"04787910",
		"city":"Sa\u0303o Paulo",
		"houseNumberOrName":"",
		"stateOrProvince":"SP",
		"country":"BR"
	},
	"deliveryAddress":{
		"street":"Roque Petroni Jr",
		"postalCode":"04787910",
		"city":"Sa\u0303o Paulo",
		"houseNumberOrName":"",
		"stateOrProvince":"SP",
		"country":"BR"
	},
	"amount":{
		"currency":"BRL",
		"value":85779
	},
	"reference":"12000000049",
	"fraudOffset":"0",
	"browserInfo":{
		"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
		"acceptHeader":"*\/*"
	},
	"enableOneClick":true,
	"enableRecurring":false,
	"socialSecurityNumber":"56861752509",
	"selectedBrand":"boletobancario_santander",
	"shopperName":{
		"firstName":"Jose\u0301","lastName":"Silva"
	},
	"deliveryDate":"2019-03-01T14:33:08 ",
	"applicationInfo":{
		"adyenLibrary":{
			"name":"adyen-php-api-library",
			"version":"1.6.0"
		},
		"adyenPaymentSource":{
			"version":"3.0.0",
			"name":"adyen-magento2"
		},
		"externalPlatform":{
			"version":"2.3.0",
			"name":"Magento"
		}
	}
} {"is_exception":false} []
</pre>
Thx.

Cristian

**Comment by cyattilakiss** [comment]
Hi @nrsWebs ,

I've checked your request Json and I couldn't reproduce the issue. The problem can happen because of a misconfiguration in your merchant account in the Adyen customer area. Could you please send the same issue including your merchant account to the support@adyen.com email address so our tech support team could check your merchant account's settings? 

(Please also include my comment in your email :) )

Best,
Attila
Adyen
