### ISSUE TITLE
API param's names inconsistency

### ISSUE THREAD

**Issue by zeleniy** [Adyen/adyen-php-api-library#110]
**PHP version**: 7.2.19
**Library version**: 3.87.18
**Description**
```
$service = new Checkout(...);
$result = $service->payments(...);
```
This call returns array which contains `data` section which in turn contains `MD`, `PaReq` and `TermUrl` items. Then in case of `RedirectShopper` is should make "[POST redirect](https://docs.adyen.com/classic-integration/3d-secure/3d-secure-1/#step-2-redirect-to-the-card-issuer)" with that `data` section as POST params. And later on `TermUrl` call i will get `MD` and `PaRes`. And finally here in callback i should do next:
```
$service = new Payment(...);
$result = $service->authorise3D($params);
```
Where is `$params` contains those `MD` and `PaRes`. And in that case i get `Configuration Problem mpiImplementation` error becuse `/authorise3d` [require](https://docs.adyen.com/api-explorer/#/Payment/v46/authorise3d) `md` parameter but not `MD`.
Also it require `paResponse` but in `TermUrl` handler i got `PaRes`. Fortunately (or not) `/authorise3d` consume both.

P.S. Also if to change `API_PAYMENT_VERSION` from `v40` to `v49` (in `Adyen\Client`) it works well, but in documentation `v46` is [latest](https://docs.adyen.com/api-explorer/#/Payment/v46/authorise3d).

Could you keep your code, API and documentation consistent?

**Comment by cyattilakiss** [comment]
Hi @zeleniy ,

Thank you for the feedback. We forwarded them to our core teams. If you may have any future suggestion, please contact support@adyen.com because the library is just responsible for communicating the APIs, but not for the APIs it selves.
Thank you for the suggestions and for your understanding.

Best,
Attila
Adyen
