### ISSUE TITLE
How to use it without composer?

### ISSUE THREAD

**Issue by jitheshkt** [Adyen/adyen-php-api-library#114]
Hi,

Would like to know how to use the SDK without composer. Can't find any include.php/autoload.php/includes.php. There is no clear documentation on this either. Please respond.

**Comment by cyattilakiss** [comment]
Hi @jitheshkt ,

Unfortunately right now we don't have any other way of using the library without composer. Is it possible to install composer to your local machine and upload the vendor folder to your server? If this is possible you just need to follow the composer docs and require the autoload.php file :)

Best,
Attila
Adyen

**Comment by jitheshkt** [comment]
Never mind, I ended up using curl after all :) Thanks for the comment.
