### ISSUE TITLE
 Class 'Adyen\PrestaShop not found 

### ISSUE THREAD

**Issue by akimania** [Adyen/adyen-php-api-library#118]
**PHP version**: 17.2
**Library version**: last
**Description**
prestashop 1.6.1

**_sorry for my bad language_**

it is impossible to use the module for prestashop, after installing the composer I have several errors example line 1
`Fatal error: Uncaught Error: Class 'Adyen\PrestaShop\service\Adyen\Helper\DataFactory' not found in modules/adyen/adyen.php:53 Stack trace: #0 [internal function]: Adyen->__construct() #1`
so I log in ssh and I notice that in vendor / adyen / there is no prestashop directory as indicated by the error
**'Adyen \ PrestaShop \ service \ Adyen \ Helper \ DataFactory'**, I already have to install more than one issue ever since it's the first time if you can help me

line 53
```
        $adyenHelperFactory = new \Adyen\PrestaShop\service\Adyen\Helper\DataFactory();
        $this->helper_data = $adyenHelperFactory->createAdyenHelperData(
            \Configuration::get('ADYEN_MODE'),
            _COOKIE_KEY_
        );
```

**Comment by cyattilakiss** [comment]
Hi @akimania ,

We use namespaces so it is not necessary to have a prestashop folder under the vendor folder.
Could you also please check if you have the autoload.php in the adyen/vendor folder?
Do you use the released version of the prestashop plugin or any other versions maybe?

(I will close this ticket, could you please open this issue under the prestashop repository?)

Best,
Attila
Adyen
