### ISSUE TITLE
[PW-1066] Use PSR for HTTP client

### ISSUE THREAD

**Issue by jorge07** [Adyen/adyen-php-api-library#12]
It's possible to use Guzzle to use PSR standard and have better integrations? Or php http to be agnostic...

**Comment by rikterbeek** [comment]
Hi @jorge07,

What do you mean by better integrations ?
For now we have chosen to use a custom Curl integration to keep the dependencies as minimum as possible. 

Regards,
Rik
Adyen

**Comment by jorge07** [comment]
Hi @rikterbeek 

I think it's easier deal with PSR-7 rather than a custom responses as simple arrays. Also can be difficult to integrate with other libs due to this non standard usage, and there is no options for middlewares, or a way to prepare a request to be sent... Packages like https://github.com/php-http/httplug gives you an abstraction to let the final user implement his own PSR-7 http client via DI, or you can go directly to guzzle... An standard its always better.

Another question, do you accept pull requests?

**Comment by rikterbeek** [comment]
Hi @jorge07,

We will look into your suggestion. Yes we do!

Regards,
Rik
Adyen
