### ISSUE TITLE
Idempotency-Key support

### ISSUE THREAD

**Issue by zggonzalez** [Adyen/adyen-php-api-library#121]
**PHP version**: 7.0
**Library version**: 3.0.0
**Description**

- please add support for the header Idempotency-Key:<key> in the library

**Comment by msilvagarcia** [comment]
Hey @zggonzalez ! Thanks for the suggestion. We'll plan adding this feature in the near future. :)

Cheers!
Marcos
Adyen

**Comment by zggonzalez** [comment]
Hi guys, 

We're having few issues with duplicated payment authorizations. Do you have a timeline for this? Just to understand if I need to implement the idempotency in a different way or I can wait for your API release?

Thx in advance.

**Comment by cyattilakiss** [comment]
Hi @zggonzalez 

In the #124 the idempotency key support is going to be merged soon.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
The fix is merged, I'm going to close this issue.

Best,
Attila
