### ISSUE TITLE
202 HTTP status code treated as errors

### ISSUE THREAD

**Issue by fredericbarthelet** [Adyen/adyen-php-api-library#127]
Hi,

Your current library indicates that any other response than HTT status code 200 result in an error.

https://github.com/Adyen/adyen-php-api-library/blob/c0d7a1db0634d95e6fdeb57e369d7161648bde9d/src/Adyen/HttpClient/CurlClient.php#L96

However your documentation states that interactions with MarketPay Account endpoint may results in [200 or 202](https://docs.adyen.com/marketpay/onboarding-and-verification) 

![image](https://user-images.githubusercontent.com/23530626/66462119-b1b74b00-ea7a-11e9-93bb-48837a83c05c.png)

If you want I'll produce the PR to handle every 2xx codes as OK codes.

**Comment by msilvagarcia** [comment]
Hey Frederic,

Thanks for raising the issue. If you could produce the pull request, that would be great.

Cheers!
Marcos
Adyen

**Comment by fredericbarthelet** [comment]
Hey @msilvagarcia, made a PR for this issue, could you review it ? Thanks

**Comment by cyattilakiss** [comment]
Hi @fredericbarthelet ,

I will close this ticket since the PR has been merged.
Please feel free to reopen if the issue persist.

Best,
Attila
Adyen
