### ISSUE TITLE
Unable to decrypt data

### ISSUE THREAD

**Issue by strang82** [Adyen/adyen-php-api-library#138]
**PHP version**: 7.2.24
**Library version**: 4.2.0
**Description**
Hi,
I'm facing an "Unable to decrypt data" exception (status 422) while trying to integrate a card payment using secured fields, as described in the documentation:
https://docs.adyen.com/checkout/drop-in-web#step-2-add-drop-in

```php
$paymentData = filter_input(INPUT_POST, 'payment_data');
$paymentMethod = json_decode($paymentData, true);

$result = $service->payments([
    "amount" => array(
      "currency" => "EUR",
      "value" => 1000
    ),
    "reference" => $order_key,
    "paymentMethod" => $paymentMethod['paymentMethod'],
    "returnUrl" => "http://{$_SERVER['HTTP_HOST']}/return.php",
    "merchantAccount" => $merchant_account
  ]);
```

In addition, the same problem is present testing the api with the api explorer:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v51/payments__example_payments-card-securedfields

`Error code: 174. Unable to decrypt data.`
```js
{
  "status": 422,
  "errorCode": "174",
  "message": "Unable to decrypt data",
  "errorType": "validation"
}
```

Thanks for your support.
Massimo

**Comment by cyattilakiss** [comment]
Hi @strang82 ,

Can you please contact support@adyen.com because this could be more like an API issue than a library issue. Can you please send them the request and the response object so they can see if there is any issue with the request parameters that is sent.

I will close the ticket for now.

Best,
Attila
Adyen

**Comment by strang82** [comment]
Ok thanks.

**Comment by PoojaPragati1401** [comment]
Any update on this issue?
