### ISSUE TITLE
Make payouts

### ISSUE THREAD

**Issue by SwiTool** [Adyen/adyen-php-api-library#15]
We can't make payouts with that library. Is that a planned functionnality that we'll can use ?

https://docs.adyen.com/developers/payout-manual

**Comment by rikterbeek** [comment]
Hi @SwiTool,

Definitely something we want to add in the future. At the moment we are very busy with our merchants before the holiday seasons so we can't add this on a short term.

Regards,
Rik
Adyen

**Comment by SwiTool** [comment]
@rikterbeek It shouldn't take days to do it. Would you have time to dig into and accept a PR ?

**Comment by rikterbeek** [comment]
Hi @SwiTool,

I know it is not that much only this month we are focussing on helping our merchants to go live before the holiday season. Yes ofcourse we do, we can review the PR and accept it.

Regards,
Rik
Adyen

**Comment by SwiTool** [comment]
@rikterbeek when will it be available on master?

**Comment by rikterbeek** [comment]
Hi @SwiTool,

This is now released and available in the master. We highly appreciate your PR. Could you reply on the mail that you already send to us and provide us your address details. We will send you a gift to appreciate making a contribution to our code.

Regards,
Rik
Adyen

**Comment by SwiTool** [comment]
Hey @rikterbeek, I never received your gift. I don't know if you sent it.. But nvm ;)

**Comment by rikterbeek** [comment]
Hi @SwiTool,

Oh that is weird it was send end of november. Could you reply on the mail where your address was in then I will check with our team what happened with the package.

Regards,
Rik
Adyen
