### ISSUE TITLE
How to get username and password

### ISSUE THREAD

**Issue by khyatibhojawala** [Adyen/adyen-php-api-library#155]
I have implemented this code and it's throwing error **Fatal error: Uncaught Adyen\AdyenException: Invalid Merchant Account in C:\wamp64\www\xmiu\vendor\adyen\php-api-library\src\Adyen\HttpClient\CurlClient.php on line 279**
**Adyen\AdyenException: Invalid Merchant Account in C:\wamp64\www\xmiu\vendor\adyen\php-api-library\src\Adyen\HttpClient\CurlClient.php on line 279**

Can anyone please tell me from where did I get the username and password.
 ==> $client->setUsername("YOUR USERNAME");
==> $client->setPassword("YOUR PASSWORD");

**Comment by msilvagarcia** [comment]
Hey @khyatibhojawala !

To access these endpoints you need to provide an API Key and Merchant Account instead. You can find these information in the Customer Area, and Tech Support (support@adyen.com) will be happy to help you find it out.

If you have any issues with the plugin itself, feel free to create a new issue.

Cheers!
Marcos
Adyen
