### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by cangelis** [Adyen/adyen-php-api-library#163]
**Library version**:  5.x.x
**Description**

Can you please share the release schedule so we can plan our releases accordingly as the library already released doesn't meet the official documentation?

**Comment by msilvagarcia** [comment]
Hey @cangelis ,

We don't have a release schedule for the plugin. As we add features or fix bugs that are ready to be release, we do so.

Could you describe what issues you face with the documentation?

Kind regards,
Marcos
Adyen
