### ISSUE TITLE
Facing issue during installation - monolog/monolog 2.0.2

### ISSUE THREAD

**Issue by rajurajpurohit** [Adyen/adyen-php-api-library#173]
**PHP version**: PHP 7.2
**Library version**: ^6.0
**Description**
Facing issue during installation - monolog/monolog 2.0.2 with Laravel. Package requires a lower version of monolog and laravel is having higher version (conflict with version).

**Comment by roman-ali** [comment]
I'm having the same issue.

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  **Problem 1**
    - Installation request for adyen/php-api-library ^6.0 -> satisfiable by adyen/php-api-library[6.0.0].
    - Conclusion: remove monolog/monolog 2.0.0
    - Conclusion: don't install monolog/monolog 2.0.0
    - adyen/php-api-library 6.0.0 requires monolog/monolog ~1.16 -> satisfiable by monolog/monolog[1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.x-dev].
    - Can only install one of: monolog/monolog[1.16.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.17.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.17.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.17.2, 2.0.0].
    - Can only install one of: monolog/monolog[1.18.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.18.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.18.2, 2.0.0].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.2, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.3, 2.0.0].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.0].
    - Installation request for monolog/monolog (locked at 2.0.0) -> satisfiable by monolog/monolog[2.0.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by Aleffio** [comment]
Hi @rajurajpurohit and @roman-ali ,

Thanks for raising the issue and providing the details,
we are providing a fix for it and will be merged soon,

Kind Regards,
Alessio
Adyen

**Comment by WiktorPacer** [comment]
PHP Version: 7.3
Package version: ^6.2
Description: Problem during installation with Laravel version 7.6.2.
` 
Problem 1
    - Installation request for adyen/php-api-library ^6.2 -> satisfiable by adyen/php-api-library[6.2.0].
    - Conclusion: remove monolog/monolog 2.0.2
    - Conclusion: don't install monolog/monolog 2.0.2
    - adyen/php-api-library 6.2.0 requires monolog/monolog ^1.16 -> satisfiable by monolog/monolog[1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.x-dev].
    - Can only install one of: monolog/monolog[1.16.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.3, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.4, 2.0.2].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.2].
    - Installation request for monolog/monolog (locked at 2.0.2) -> satisfiable by monolog/monolog[2.0.2].
`

I see this issue was resolved but I think this change of composer.json caused the problem - https://github.com/Adyen/adyen-php-api-library/commit/7097f0d8856ff7ec310f12f569548d50eac7e80d

**Comment by cyattilakiss** [comment]
Hi @WiktorPacer 

Yes that one caused the issue. Please use the latest version of the library where we don't require a specific version of the monolog anymore. If you would still keep using the one which you are using now just change the composer.json as a quick fix, that will work as well.

Best,
Attila
Adyen
