### ISSUE TITLE
Invalid PayWithGoogle token

### ISSUE THREAD

**Issue by mohd999** [Adyen/adyen-php-api-library#181]
**PHP version**:5.5.9
**Library version**: 1
**Description**

- After go live I got error :Invalid PayWithGoogle token.. Other payment methods working fine.

**Comment by mohd999** [comment]
Library version: 6.0.1

**Comment by cyattilakiss** [comment]
Hi @mohd999 ,

This one looks like a configuration issue and not library related issue. Could you please reach out to our support at support@adyen.com? They are going to be able to assist you better with your question.

Best,
Attila
Adyen
