### ISSUE TITLE
Error when using PreAuth on Terminal API (Cloud Sync)

### ISSUE THREAD

**Issue by alex-grau** [Adyen/adyen-php-api-library#188]
**PHP version**: 7.2.24
**Library version**: 6.0.1
**Description**
I'm trying to PreAuth with the Terminal API (Cloud Sync https://docs.adyen.com/point-of-sale/pre-authorisation).

From documentation, if we add "authorisationType=PreAuth" to "SaleToAcquirerData" it should work. When we make this Request from Postman or own curl library, it works, but when using this library it does not work.
Debugging code we see that Adyen\Service\AbstractResource changes this field on the method handleApplicationInfoInRequestPOS, it adds:
`"applicationInfo":{"adyenLibrary":{"name":"adyen-php-api-library","version":"6.0.1"}}` and changes format to base64encoded json (without urlencode!).

Then we receive a NonAuthorized error code.

**Comment by cyattilakiss** [comment]
Hi @alex-grau ,

Thank you for opening the issue. Could you please send us the object (with masked sensitive data) you send in the library request? 

> Debugging code we see that Adyen\Service\AbstractResource changes this field on the method handleApplicationInfoInRequestPOS, it adds: "applicationInfo":{"adyenLibrary":{"name":"adyen-php-api-library","version":"6.0.1"}} and changes format to base64encoded json (without urlencode!).

Adding the `applicationInfo` is an expected behaviour also reformatting should be fine but maybe there is a mismatch in that.

Thank you in advance,
Attila
Adyen

**Comment by AlexandrosMor** [comment]
Hello @alex-grau,

Do you have any updates about the issue?  Are you still able to send us the object that you send in the library request so we can investigate it further?

kind regards,
Alexandros

**Comment by cyattilakiss** [comment]
Hi @alex-grau ,

Due to inactivity I am closing this issue but please feel free to reopen it in case the issue is still there.

Best,
Attila
Adyen

**Comment by alex-grau** [comment]
Hello! Sorry, I was out and not using this library again, until today (and the error still exists, at least for me). The problem is using \Adyen\Service\PosPayment($client);

This is the current code:

$adyenClient = new Adyen\Client();
$adyenClient->setApplicationName($applicationName);
$adyenClient->setXApiKey($apiKey);
$adyenClient->setMerchantAccount($accountId);
$adyenClient->setEnvironment(Adyen\Environment::TEST);

$request = [
    'SaleToPOIRequest' => [
        'MessageHeader' => [
            'ProtocolVersion' => '3.0',
            'MessageClass' => 'Service',
            'MessageCategory' => 'Payment',
            'MessageType' => 'Request',
            'SaleID' => $serialNumber,
            'ServiceID' => '' . (string)rand(1000000, 9000000) . '',
            'POIID' => $serialNumber
        ],
        'PaymentRequest' => ['SaleData' => [
            'SaleTransactionID' => [
                'TransactionID' => (string)rand(1234, 5678),
                'TimeStamp' => (new DateTime())->format(DateTime::ATOM)
            ],
            'SaleToAcquirerData' => 'authorisationType=PreAuth'
        ],
            'PaymentTransaction' => [
                'AmountsReq' => [
                    'Currency' => 'USD',
                    'RequestedAmount' => 150.00
                ],
            ]
        ]
    ]
];

$service = new Adyen\Service\PosPayment($adyenClient);

$response = $service->runTenderSync($request);

var_dump($response);

Response.result is "Failure" because it seems that I don't have permisions, BUT, I receive an additional warning in AdditionalResponse: "eyAid2FybmluZ3MiOiAiQXQgU2FsZVRvUE9JUmVxdWVzdCwgZmllbGQgbWVyY2hhbnRBY2NvdW50OiBVbmV4cGVjdGVkIiwgIm1lc3NhZ2UiOiAiU2FsZSB0byBBY3F1aXJlciBEYXRhOiBOb3RBbGxvd2VkIFZhbHVlOiBleHRyYSBkYXRhLCBSZWFzb246IEZhaWxlZCB2YWxpZGF0aW9uIiB9", it means "{ "warnings": "At SaleToPOIRequest, field merchantAccount: Unexpected", "message": "Sale to Acquirer Data: NotAllowed Value: extra data, Reason: Failed validation" }"

But I haven't added that "merchantAccount" on the SaleToPOIRequest. I checked the library and it's on the Adyen\Service\AbstractResource:122, inside addDefaultParametersToRequest method.
