### ISSUE TITLE
Adyen 010 refused payment

### ISSUE THREAD

**Issue by ikalangita** [Adyen/adyen-php-api-library#20]
Getting 
`(
    [errorType] => security
    [errorCode] => 010
    [message] => Not allowed
    [pspReference] => 8614834610386710
    [status] => 403
)`

When trying to pay from : (I set correctly username and password with merchant account)

`$request = array(
	 	"merchantAccount" => "XXXXX",   
	 	"amount.currency" => "EUR",
	 	"amount.value" => "1990",
	 	"reference" => "TEST-PAYMENT-" . date("Y-m-d-H:i:s"),
	 	//"shopperIP" => "ShopperIPAddress",
	 	"shopperEmail" => "shoppermail@gmail.com",
	 	"shopperReference" => "12348",
	 	"fraudOffset" => "0",

	 	"card.billingAddress.street" => "Simon Carmiggeltstraat",
	 	"card.billingAddress.postalCode" => "1011 DJ",
	 	"card.billingAddress.city" => "Amsterdam",
	 	"card.billingAddress.houseNumberOrName" => "6-50",
	 	"card.billingAddress.stateOrProvince" => "",
	 	"card.billingAddress.country" => "NL",

	 	"card.expiryMonth" => "06",
	 	"card.expiryYear" => "2018",
	 	"card.holderName" => "John Smith",
	 	"card.number" => "4111111111111111",
	 	"card.cvc" => "004",
	 	);
	 
	 $ch = curl_init();
	 curl_setopt($ch, CURLOPT_URL, "https://pal-test.adyen.com/pal/servlet/Payment/v18/authorise");
	 curl_setopt($ch, CURLOPT_HEADER, false); 
	 curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC  );
	 curl_setopt($ch, CURLOPT_USERPWD, "ws@myCompany:myPassword");   
	 curl_setopt($ch, CURLOPT_POST,1);
	 curl_setopt($ch, CURLOPT_POSTFIELDS,http_build_query($request));
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

	 $result = curl_exec($ch);
	 
	 if($result === false)
	 	echo "Error: " . curl_error($ch);
	 else{
	 	/**
		 * If the payment passes validation a risk analysis will be done and, depending on the
		 * outcome, an authorisation will be attempted. You receive a
		 * payment response with the following fields:
		 * - pspReference: The reference we assigned to the payment;
		 * - resultCode: The result of the payment. One of Authorised, Refused or Error;
		 * - authCode: An authorisation code if the payment was successful, or blank otherwise;
		 * - refusalReason: If the payment was refused, the refusal reason.
		 */ 

	 	parse_str($result,$result);
	 	echo "==== OUTPUT ";
	 	print_r(($result));
	 }
	 
	 curl_close($ch);`

Thank you

**Comment by rikterbeek** [comment]
Hi @ikalangita,

By default you have not the permission to do full API payments. This is only possible if you are PCI compliant.  Best option is to encrypt the card data on the client side with our CSE library and send over the payment encrypted data.

Regards,
Rik
Adyen

**Comment by ikalangita** [comment]
Hello, 
Thank you, yes I have encrypted the data with CSE, but I want more data (like shopper email) from response when authorized, is it possible?
Thanks again.

**Comment by rikterbeek** [comment]
Hi @ikalangita,

Why do you want shopper email from us? you should already know this before sending in the request to us.

Regards,
Rik
Adyen
