### ISSUE TITLE
Is there any official Omnipay integration?

### ISSUE THREAD

**Issue by elfeffe** [Adyen/adyen-php-api-library#201]
You can see that Omnipay has a lot of integrations.
https://omnipay.thephpleague.com/gateways/community/

Also it belongs to PHP League, what assures a high-quality code. And it's used by a lot of projects because it is compatible with a lot of payment processors.

But where is the official support for it?
I want to use Adyen with Laravel, and there is no way unless developing all my code, I think it can help Adyen to integrate with more projects as Omnipay is already there.

**Comment by AlexandrosMor** [comment]
Hello @elfeffe,

It is not in our year goals and at the moment there is no discussion around it. If there is a business case for it in the future maybe we might consider to work with the omnipay.

Kind regards,
Alexandros
