### ISSUE TITLE
Laravel is not recommended?

### ISSUE THREAD

**Issue by elfeffe** [Adyen/adyen-php-api-library#202]
A normal person understands that you offer a PHP API to integrate into your PHP projects.
But your customer support told me that Laravel https://github.com/laravel/laravel "is not recommended".
So if Laravel is "not recommended", which systems are recommended?
Can I integrate your PHP API into my system? Or Adyen can be used just with a list of systems?
Which ones?
What's the purpose of this package if it can be integrated into your system but then Adyen will not recommend and maybe not approve it as they did with Magento 1?

**Comment by msilvagarcia** [comment]
Hey @elfeffe 

Apologies for the miscommunication from our support team. What they meant was we don't give recommendations on platforms and frameworks for our merchants. However, you will be able to process payments using an e-commerce built with Laravel.

Kind regards,
Marcos
Adyen
