### ISSUE TITLE
Support for Adyen MarketPay

### ISSUE THREAD

**Issue by holtkamp** [Adyen/adyen-php-api-library#21]
Currenly looking at [Adyen MarketPay](https://docs.adyen.com/developers/marketpay), which seems quite interesting to be able to split incoming payments. However this API seems not to support this yet? Am I missing something, or is it scheduled to be supported?

**Comment by rikterbeek** [comment]
Hi @holtkamp,

Correct this is a new product we offer but more for the bigger businesses to automate this kind of processes. If we have more demand for it we can include it into our API library.

Regards,
Rik
Adyen

**Comment by holtkamp** [comment]
Ok, thanks for the swift response. 

In case you guys are up for the challenge, I would advise to combine

https://github.com/goetas-webservices/wsdl2php

with your WSDL

https://cal-test.adyen.com/cal/services/Account/v1?wsdl

to generate intermediate PHP classes. 

Maybe (some day) I will experiment a bit as well 😄 

Closing issue!

**Comment by gabma** [comment]
Hi,
Interested in having this compatible as well...
