### ISSUE TITLE
How to use Monolog 2? Laravel 7 (and latest software) uses it, so i can't install your package.

### ISSUE THREAD

**Issue by elfeffe** [Adyen/adyen-php-api-library#210]
You know that you are very strict about using latest software to accomplish PCI.
But I can't install your package in my latest Laravel 7 because you use Monolog 1.
Is there any branch using Monolog 2?

**Comment by acampos1916** [comment]
Hello @elfeffe,

Version 7 of this library is being released shortly and it specifies monolog >=1.16 #209.

Cheers,
Ángel
