### ISSUE TITLE
adyenImplementation.js errors and returns error code 419

### ISSUE THREAD

**Issue by kev1nC** [Adyen/adyen-php-api-library#213]
I'm running this on a local laravel project. When I clone the "adyen-implementation-demo" one, it works. Now, copying exactly the files and integrating it to our project gives me an error 419 ( Laravel's "Page Expired). I already tried every solutions in stackoverflow :D So I'm here to flag it as a bug now.

**Comment by AlexandrosMor** [comment]
Hello @kev1nC,

We do not support any adyen-implementation-demo repository. We maintain and update the repositories under the Adyen organisation. 
I believe your question is unrelated to php library. If you have more questions please do not hesitate to open a new issue. 

kind regards,
Alexandros
