### ISSUE TITLE
handleResultError bug

### ISSUE THREAD

**Issue by jwaguet** [Adyen/adyen-php-api-library#217]
In Adyen/HttpClient/CurlClient::handleResultError, we json decode $result param and after we have a check if we have "message" and "errorCode" but i have response like this : 

```
 array:2 [
  "invalidFields" => array:1 [
    0 => array:3 [
      "errorCode" => 44
      "errorDescription" => "The document 'XXXXpdf' has already been uploaded"
      "fieldType" => array:2 [
        "field" => "AccountHolderDetails.Document.document"
        "fieldName" => "document"
      ]
    ]
  ]
  "pspReference" => "XXXX"
```

So, the if must check ['invalidFields']['errorDescription'] and ['invalidFields']['errorCode']. Without this, errorCode is always to 0

**Comment by AlexandrosMor** [comment]
Hello @jwaguet,
Thank you for raising this issue. What is the request or the api that you are calling? Furthermore  can you explain us more what do you mean here 
```
So, the if must check ['invalidFields']['errorDescription'] and ['invalidFields']['errorCode']. Without this, errorCode is always to 0

```
kind regards,
Alexandros

**Comment by jwaguet** [comment]
The issue come when i call the function uploadDocument from the Account class. This function thrown an ADYEN exception (you can see the dump in my first message).
In a try / catch block, i try to dump $e->getCode and result is alaways to 0.
So i try to understand why and the issue come from the handleResultError function in Adyen/HttpClient/CurlClient at line 277

**Comment by cyattilakiss** [comment]
Hi @jwaguet ,

In the PR #242 , handling the error code has been updated. Does this solve the issue you face?

Best,
Attila
Adyen

**Comment by jillingk** [comment]
@jwaguet,

I'm closing the ticket, because I assume your issue has been solved. If this is not the case please let me know and I'll look into it. 

Best, Jilling
Adyen
