### ISSUE TITLE
How to search by "Merchant Reference" field

### ISSUE THREAD

**Issue by gnumoksha** [Adyen/adyen-php-api-library#22]
I'm unable to find an API endpoint to search a payment by its "Merchant Reference"· Is it possible?

**Comment by rikterbeek** [comment]
Hi @gnumoksha,

We do not have an API endpoint to search for a payment not sure what you want to do though ?
With our notifications you will get back the status of the payments.

Regards,
Rik
Adyen

**Comment by gnumoksha** [comment]
Hi @rikterbeek, thank you for the quick response.

I have some payments that doesn't have the correct response from adyen, because of a bad implementation on my side, and I want to search by "Merchant Reference" without spending time manually.

**Comment by rikterbeek** [comment]
Hi @gnumoksha,

We don't have this kind of API to check status. What you can do is implement a notification handler so you know exactly what the status is. You can setup multiple endpoints for notifications in your merchantAccount.

Regards,
Rik
Adyen

**Comment by vladilsav10** [comment]
Hi @rikterbeek 

I know this a long closed issue, but I am curious why there is no endpoint to search using the merchant reference? To me, it seems like a really useful endpoint to have for some rare cases,
