### ISSUE TITLE
[PW-3048] Update Checkout API version

### ISSUE THREAD

**Issue by mpesari** [Adyen/adyen-php-api-library#222]
I'm currently creating a new integration, starting with the simple Pay by Link API. However, I ran into some problems with the PHP library, I hope there's an easy way to solve this.

**Is your feature request related to a problem? Please describe.**

The `/paymentLinks` API v52 currently used by the PHP library does not respond with the documented set of parameters. Notably, the useful `id` field is missing: https://docs.adyen.com/api-explorer/#/CheckoutService/v52/post/paymentLinks__resParam_id

The `id` field is actually returned by API v53.

**Describe the solution you'd like**

My solution would be to bump the API version used by the PHP library. I guess it might break something internal in the library.

**Describe alternatives you've considered**

Add `Adyen\Client::setApiCheckoutVersion(int $version)` or similar way to use custom API version. I guess it might break something internal in the library.

**Additional context**

The tutorial suggests saving the payment link response `id` and using it to match with a notification call: https://docs.adyen.com/checkout/pay-by-link#create-payment-links-through-api

This is reasonable, but with the current state of the PHP library we have to parse the response `url` and guess which part, if any, should be saved as an identifier for the payment.

**Comment by floflock** [comment]
+1 here!

I think, it need a little bit more work since the API version have different behaviours. However, an upgrade would be great.

**Comment by cyattilakiss** [comment]
Hi @mpesari , @floflock 

We have created the ticket in our system to create the PR to update the checkout API endpoints to the latest version.
We are going to decide about picking this up in the next couple of sprints after we finish with other priority items.
Thank you for your patience.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @mpesari , @floflock

The version bump has been released in the v8.0.0
I will close this issue for now but please feel free to reopen it if you face any issue regarding this.

Best,
Attila
Adyen
