### ISSUE TITLE
010 Not allowed error

### ISSUE THREAD

**Issue by sdipchikov** [Adyen/adyen-php-api-library#23]
Hello I receive this error when using your code sample. Can you please advice where the problem might be the web service user I'm using has all the available permissions (see attached). Thank you in advance!
<img width="1097" alt="screen shot 2017-04-27 at 2 04 29 pm" src="https://cloud.githubusercontent.com/assets/1019105/25480679/762837b4-2b52-11e7-919d-eca334313280.png">

**Comment by rikterbeek** [comment]
Hi @sdipchikov,

You need to use cards through CSE instead of sending us the raw card data.

Regards,
Rik
Adyen

**Comment by sdipchikov** [comment]
Hi, thanks for the response. 
I'm trying to do a test call using the "Create Payment Request on Test:" example as per your documentation? Do I need to use CSE there as well?


Best,
Stoyan

**Comment by rikterbeek** [comment]
Hi @sdipchikov,

The test are using full api. See cse example here:
http://adyen.github.io/adyen-php-api-library/payment.html

Regards,
Rik
Adyen

**Comment by sdipchikov** [comment]
Got it! Thanks! Will test now!

**Comment by wesweat** [comment]
@sdipchikov did you manage to use the sample code??? i am getting 

> Fatal error: Uncaught exception 'Adyen\AdyenException' with message 'Not allowed'

**Comment by greeven** [comment]
Me too! The example doesn't work.

**Comment by oxodesign** [comment]
@wesweat @greeven im getting the same thing, did you guys figure out?

`Fatal error: Uncaught exception 'Adyen\AdyenException' with message 'Not allowed'`

But I can find the transaction under "Transactions > Payments" with status "Refused".

**Comment by greeven** [comment]
Not yet. Haven't looked into this more @oxodesign .
