### ISSUE TITLE
AdyenException: errorCodes corrupted

### ISSUE THREAD

**Issue by patrickmyh** [Adyen/adyen-php-api-library#240]
**Describe the bug**
When doing certain requests to Adyen, e.g. a /payment request to the checkout-API, in case of an error, an AdyenException is thrown. Adyen returns several error codes as can be seen here:

https://docs.adyen.com/development-resources/error-codes

\Adyen\HttpClient\CurlClient's "handleResultError" method maps such an error-response to an AdyenException that is then thrown:

```
protected function handleResultError($result, $logger)
    {
        $decodeResult = json_decode($result, true);
        if (isset($decodeResult['message']) && isset($decodeResult['errorCode'])) {
            $logger->error($decodeResult['errorCode'] . ': ' . $decodeResult['message']);
            throw new AdyenException(
                $decodeResult['message'],
                $decodeResult['errorCode'],
                null,
                $decodeResult['status'],
                $decodeResult['errorType'],
                isset($decodeResult['pspReference']) ? $decodeResult['pspReference'] : null
            );
        }
        $logger->error($result);
        throw new AdyenException($result);
    }
```

However, there's a problem. By interface, the Exception's code property is an int type. But Adyen also returns codes like "14_005". AdyenException's constructor then casts this to an integer, thus everything after the "_" gets truncated.

```
class AdyenException extends Exception
{ 
[...]
    public function __construct(
    [...]
        $errorType = null,
        $pspReference = null
    ) {
    [...]
    parent::__construct($message, (int)$code, $previous);
```

As you can see in the documentation, there's quite a lot and important codes that are affected.
So what can we do? I'd suggest adding another parameter (adyenErrorCode e.g.)

I might add a PR, if there's a decision from the maintainer.

**To Reproduce**
Just do a payments-request, let's say SEPA Direct Debit, with the payload:

```
{
   "reference":"YOUR_ORDER_NUMBER",
   "amount":{
   "currency":"EUR",
   "value":1000
   },
   "paymentMethod":{
   "type":"sepadirectdebit",
   "sepa.ownerName":"4",
   "sepa.ibanNumber":"4"
   }
}
```

Result: The errorCode's meaning is lost. 

which triggers a code "14_004", "Missing payment method details".

**Expected behavior**
A way to get the original error code as a string.

**Comment by patrickmyh** [comment]
..another way could be to remove the "_" in the error code, so that it could remain an int. Though I don't see any collisions to exisiting error codes from Adyen it might break exisitng implementations relying on truncated codes. 

So an additional string parameter as a constructor argument in AdyenException might be the best way imho.

Pls. advise Adyen, and I'll do a pull request.

**Comment by acampos1916** [comment]
Hello @patrickmyh, thanks for opening this issue,

You're right, the response error code is usually a string. A PR would be great, how about creating a new string property for the error code and use the old int code for the httpStatus?

Cheers,
Ángel
