### ISSUE TITLE
Exception error code BC break in minor version 8.1.0

### ISSUE THREAD

**Issue by rossmotley** [Adyen/adyen-php-api-library#250]
**Describe the bug**

#242 introduced a breaking change in the minor release 8.1.0

The Adyen error code is now mapped to "status" instead of "errorCode". We were using $exception->getCode() to handle Adyen errors, as of 8.1.0 we have to use $exception->getAdyenErrorCode()

With semantic versioning $exception->getCode() should have been kept the same until a major version release (e.g. 9.0.0)

I would suggest releasing 8.2.0 with this change reverted - [as per Semantic Versioning](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version).

(discovered by @oradwell)

**Comment by peterojo** [comment]
Hi @rossmotley @oradwell, thanks for pointing this out, and sincere apologies for the delay in responding. We've released a patch 8.1.1 to make the `getCode()` function backward compatible in version 8, and to be SEMVER compliant.
We do recommend, if you haven't already, that you consider switching to the latest version of the library.
