### ISSUE TITLE
Checkout API v67 Support

### ISSUE THREAD

**Issue by patrickmyh** [Adyen/adyen-php-api-library#258]
Adyen just released the Checkout API v67, which brings a lot of improvemets for 3DSecure handling and makes it a lot easier.
Do you plan to support this in the near future?

https://docs.adyen.com/online-payments/release-notes#mar-1st-2021

**Comment by peterojo** [comment]
Hi @patrickmyh,
Yes we have plans to update the library to support the new version.
I will give an update when we have a release schedule.
