### ISSUE TITLE
CurlClient exception handling

### ISSUE THREAD

**Issue by przemeko** [Adyen/adyen-php-api-library#27]
In `Adyen\HttpClient\CurlClient` there are 2 private methods:
- handleCurlError
- handleResultError

They both returns the same exception:  `\Adyen\AdyenException`
So there's no way to distinguish connection errors and "api result" errors (i.e that would allow to decide to retry payment or not.)

My proposal is to return two different exceptions:
- `\Adyen\ConnectionException`in handleCurlError
- `\Adyen\AdyenException` in handleResultError

**Comment by rikterbeek** [comment]
Hi @przemeko,

I understand your issue. There is a way to distinguish the error based on the message of the exception but would be indeed better to use different exception classes so you can create your own catches. I will make a change in the code to make this possible.

Regards,
Rik
Adyen
