### ISSUE TITLE
Tag a new release for the HOP service

### ISSUE THREAD

**Issue by kevin-emo** [Adyen/adyen-php-api-library#271]
Hello,

I have been waiting for the following PR to be merged https://github.com/Adyen/adyen-php-api-library/pull/248 , in order to be able to use the Hop service.

However, as pointed out by the Adyen support, it has already been implemented in #266 on the "develop" branch, independently of the previous PR.

As it does not seem to involve any BC break, would you mind to tag this release, so that I can target a production ready version in my application, please ?

Thanks.

**Comment by peterojo** [comment]
#266 is now released in version 10.1.0
Closing this issue :)
