### ISSUE TITLE
Recurring /scheduleAccountUpdater not present in package

### ISSUE THREAD

**Issue by iSyedTausif** [Adyen/adyen-php-api-library#278]
**Issue**
Schedule account updater endpoint is not present in package under recurring service.

**Solutions**
- /scheduleAccountUpdater is supported by this package (Adyen ref. doc, https://docs.adyen.com/api-explorer/#/Recurring/v49/post/scheduleAccountUpdater)

**Comment by jillingk** [comment]
Hi @iSyedTausif,

Apologies for the extremely late respons. I opened a PR #373 to add the endpoint. 

Best, Jilling
Adyen
