### ISSUE TITLE
No status send in error exception

### ISSUE THREAD

**Issue by przemeko** [Adyen/adyen-php-api-library#29]
[Error handling api docs](https://docs.adyen.com/developers/payments/test-cards/create-test-cards/error-handling#responsemapping) says that every error response  contains these data:
```
{
    "errorType" : "security",
    "errorCode" : "901",
    "message" : "Invalid Merchant Account",
    "status" : "403"
}
```
But in library method that handle this kind of errors (`handleResultError` in `CurlClient`) there are forwarded ONLY **message** and **errorCode**.
```
if(isset($decodeResult['message']) && isset($decodeResult['errorCode'])) {
    $logger->error($decodeResult['errorCode'] . ': ' . $decodeResult['message']);
    throw new \Adyen\AdyenException($decodeResult['message'], $decodeResult['errorCode']);
}
```
It would be a lot easier to handle errors if exceptions throws by "adyen-php-api-library" contains also **status** field.

Regards
Przemek

**Comment by rikterbeek** [comment]
Hi @przemeko,

Thanks for you comment. Yes this makes sense, see the change above. Is this change the solution that you were looking for?

Regards,
Rik
Adyen

**Comment by przemeko** [comment]
Hi @rikterbeek 

Yes, it solves issue. Great job!

Regards
Przemek
