### ISSUE TITLE
Monolog conflict using 'composer require'

### ISSUE THREAD

**Issue by roelandp** [Adyen/adyen-php-api-library#3]
New API looks great, would love to integrate this. However when I try to install via the `composer require adyen/php-api-library` there seems to be a conflict with the monolog versioning.... It's tiny but annoying, would rather not fork, would it be as simple as updating your composer.json as per [this commit](https://github.com/Adyen/adyen-php-api-library/commit/506feb2b3a86fdbe6703d4925005b53429b676b5) from @rikterbeek ? 

Here is the error: 

> `composer require adyen/php-api-library`
> _(....processing ..... )_
>
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: monolog/monolog[1.18.0, 1.16.0].
>     - Can only install one of: monolog/monolog[1.16.0, 1.18.0].
>     - Can only install one of: monolog/monolog[1.16.0, 1.18.0].
>     - adyen/php-api-library 1.0.0 requires monolog/monolog 1.16.0 -> satisfiable by monolog/monolog[1.16.0].
>     - Installation request for adyen/php-api-library ^1.0 -> satisfiable by adyen/php-api-library[1.0.0].
>     - Installation request for monolog/monolog == 1.18.0.0 -> satisfiable by monolog/monolog[1.18.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

Composer tries to install the master 1.0.0 branch, so I'm not sure if the #1 which is not yet pushed to the release version will fix this? If so, when would you update to a new release? thank you!

**Comment by rikterbeek** [comment]
Hi roelandp,

Thanks, Yes #1 should solve your issue. This was not in our master branch so that's why. I just did a new release of our Library 1.0.1 this should solve your issue.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @roelandp ,

Did this solve your issues ?

Regards,
Rik
Adyen

**Comment by roelandp** [comment]
Yes thanks happily working! 

Now trying if I can get everything working together. 

I couldnt find a "create hpp url or form params" in this api right?

Pls correct me if i'm wrong! Thanks Rik!

**Comment by rikterbeek** [comment]
Hi @roelandp,

This library is used for all API connection to the Adyen platform. This is just create a webUrl for paying not something this library is responsible for.

Regards,
Rik
Adyen
