### ISSUE TITLE
Does this lib supports verify endpoint?

### ISSUE THREAD

**Issue by bpetar** [Adyen/adyen-php-api-library#33]
Im trying to integrate PHP backend with Android app, Android client implementation mentions 'setup' and 'verify' API endpoints to be implemented by server:
https://docs.adyen.com/developers/in-app-integration?platform=inapp-android

But I dont see these endpoints implemented in this API library?

**Comment by rikterbeek** [comment]
Hi @bpetar,

The endpoints used for the In-App application are not yet in the library.
What you can do is implement custom API interaction for this see our documentation for more information how to do this: https://docs.adyen.com/developers/in-app-integration?platform=inapp-ios

What we will do is integrate all our APIs into this library but that will take some time so better for now to build the custom integration.


Regards,
Rik
Adyen
