### ISSUE TITLE
Please supply paymentDetails when using recurring payment library 

### ISSUE THREAD

**Issue by gaurav1992** [Adyen/adyen-php-api-library#34]
I am using recurring payment to add customer card on Adyen with the help of given code which is 

```           
            $client = new \Adyen\Client();
            $client->setApplicationName("");
            $client->setUsername("");
            $client->setPassword("");
            $client->setEnvironment(\Adyen\Environment::TEST);
             $service = new \Adyen\Service\Payment($client);
             $recurring = array('contract' => \Adyen\Contract::RECURRING);
             $amount = array(
                "value" => 2400,
                "currency"=> "EUR"
             );
             $request = array(
                "selectedRecurringDetailReference" => "LATEST",
                "merchantAccount" => "",
                "amount" => $amount,
                "reference" => "recurring",
                "card" => $data['adyen-encrypted-data'],
                "shopperEmail" => "test@test.nl",
                "shopperReference" => "TheShopperreference",
                "recurring" => $recurring['contract'],
                "shopperInteraction" => "ContAuth"
             );
             $result = $service->authorise($request);
             print_r("Payment Result:\n");
             print_r("- pspReference: " . $result['pspReference'] . "\n");
             print_r("- resultCode: " . $result['resultCode']. "\n");
             print_r("- authCode: " . $result['authCode']. "\n");
             print_r("- refusalReason: " . $result['refusalReason']. "\n");
```

it say's **Please supply paymentDetails** I am using CSE on client side.

**Comment by rikterbeek** [comment]
Hi @gaurav1992,

Sorry for the later reply. If you are using CSE the encrypted data needs to be passed into the additionalData field as card.encrypted.json" see below:
"additionalData": {
    "card.encrypted.json": "THE ENCRYPTED DATA"
  }

Regards,
Rik
Adyen

**Comment by pradeep-sawant2501** [comment]
Hi wanted to integrate adyen using omnipay. getting this kind of output error (Please supply paymentDetails) ::
Array
(
    [status] => 422
    [errorCode] => 000
    [message] => Please supply paymentDetails
    [errorType] => validation
    [pspReference] => 881600324956070K
)

Input passed as:

<pre>Array
(
    [additionalData] => Array
        (
            [card] => Array
                (
                    [number] => 4111111111111111
                    [expiryYear] => 2030
                    [expiryMonth] => 03
                    [holderName] => Pradeep Sawant
                )

            [billingAddress] => Array
                (
                    [city] => Columbia
                    [country] => NL
                    [houseNumberOrName] => 88
                    [street] => 
                    [postalCode] => 412
                    [stateOrProvince] => MD
                )

            [executeThreeD] => false
        )

    [amount] => Array
        (
            [value] => 150000
            [currency] => EUR
        )

    [reference] => tr388384242_12456
    [merchantAccount] => Developer914ECOM
)

My code:
echo "Gateway Name: ".$gateway->getName();
                                                                            
            $card = new CreditCard(array(
               'firstName' => 'Pradeep',
               'lastName' => 'Sawant',
               'number' => '4111111111111111',
               'expiryMonth'           => '03',
               'expiryYear'            => '2030',
               'cvv'                   => '737',
               'billingAddress1'       => '88',
               'billingCountry'        => 'NL',
               'billingCity'           => 'Columbia',
               'billingPostcode'       => '412',
               'billingState'          => 'MD',
               // 'shippingCountry'       => 'GB',
               // 'shippingAddress1'      => '88',
               // 'shippingCity'          => 'Columbia',
               // 'shippingPostcode'      => '412',
            ));

            //echo "<pre>"; print_r($card);

            $response = $gateway->authorize(
                [
                    'amount'        => '1500',
                    'currency'      => 'EUR',
                    'transactionId' => 'tr388384242_12456',
                    'card'          => $card,
                    'merchantAccount' => 'Developer914ECOM',
                    //'description'   => 'Test Purchase',
                    //'returnUrl' => 'https://example.co.uk/sagepay-complete',
                ]
            )->send();

            echo "<pre>"; print_r($response->getData()); die;
