### ISSUE TITLE
Vulnerability in Adyen PHP library

### ISSUE THREAD

**Issue by AdamBodera-TomTom** [Adyen/adyen-php-api-library#348]
**Vulnerability in Adyen PHP library**
We've discovered an unsafe type comparison in HMAC validation method, please see the code below:

```
public function isValidNotificationHMAC($hmacKey, $params)
{
if (empty($params["additionalData"]) || empty($params["additionalData"]["hmacSignature"])) {
throw new AdyenException("You did not provide hmacSignature in additionalData");
}
$merchantSign = $params["additionalData"]["hmacSignature"];
unset($params["additionalData"]);
$expectedSign = $this->calculateNotificationHMAC($hmacKey, $params);

return $expectedSign == $merchantSign;
}
```

**Expected behavior**
`return $expectedSign === $merchantSign;`

**Comment by jillingk** [comment]
Hey @AdamBodera-TomTom,

Thanks a lot for bringing this to our attention. I'll be pushing the change later today!

Best, Jilling
Adyen
