### ISSUE TITLE
Adyen\ConfigInterface is missing functions

### ISSUE THREAD

**Issue by j3j5** [Adyen/adyen-php-api-library#38]
**PHP version**: all
**Library version**: 1.4.0
**Description**
The interface for the config object is missing, at least, the `getEnvironment()` function. It should be added if it's required to implement it (a service can't be created without it), an Exception is thrown (which, by the way, says `corect` instead of `correct`).

**Comment by rikterbeek** [comment]
Hi @j3j5,

You need to implement the get method from the configInterface if you want to achieve this. The service will call this method with the param "environment". This is set on the Client by setEnvironment() call.

Thanks for addressing the spelling issue this is fixed see commit above.

Regards,
Rik
Adyen

**Comment by j3j5** [comment]
No, you are right, I don't know how but I got the error that the function was missing, but double checking now you are right, it is indeed not required.

Thanks!
