### ISSUE TITLE
Adyen/Config ctor has bad annotation for $params

### ISSUE THREAD

**Issue by alan6k8** [Adyen/adyen-php-api-library#381]
**Describe the bug**
    /**
     * Config constructor.
     *
     * @param null $params
     */
    public function __construct($params = null)
    {
    // but you admit array, it should be at least ?array $params = null or even better array<string, string|somerthing else?> $params = []
    }

**To Reproduce**
just read the code

**Expected behavior**
adequate annotation/type hint 

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by jillingk** [comment]
Hi @alan6k8,

Thanks for reaching out to us with this issue. It seems indeed that for older php versions our implementation will cause some problems. Good one for catching this!

Best, Jilling
Kingma

**Comment by alan6k8** [comment]
Thanks for fixing this, the issue is not related to PHP version but to static code analysis as it detects an array being put to null method argument...
