### ISSUE TITLE
Would you welcome a CI like this?

### ISSUE THREAD

**Issue by szepeviktor** [Adyen/adyen-php-api-library#389]
https://github.com/web-auth/cose-lib/actions/runs/2868568369 👀 

- includes all my knowledge preventing very many problems
- execute checks in separate jobs: appearing as separate lines in PR UI
- does not run twice from local a branch

**Comment by jillingk** [comment]
Hi @szepeviktor,

Thanks for reaching out to us here. I will propose this to the team and let you know what their input is on this!

Best, Jilling
Adyen
