### ISSUE TITLE
Constant names for directory lookup on Client

### ISSUE THREAD

**Issue by j3j5** [Adyen/adyen-php-api-library#39]
**PHP version**: all
**Library version**: 1.4.0
**Description**
A bit of a nitpick, but the constant names for the directory lookup on the Client class are missing the `D` on `ENDPOINT`.

`ENPOINT_TEST_DIRECTORY_LOOKUP` and `ENPOINT_LIVE_DIRECTORY_LOOKUP`.

**Comment by rikterbeek** [comment]
Hi @j3j5,

Thanks for addressing this this is now fixed. see commit above.

Regards,
Rik
Adyen
