### ISSUE TITLE
ListRecurringDetails ResourceModel force inclusion of 'recurring' param but it isn't required

### ISSUE THREAD

**Issue by j3j5** [Adyen/adyen-php-api-library#40]
**PHP version**: all
**Library version**: 1.4.0
**Description**
The ResourceModel for `ListRecurringDetails` (`Adyen\Service\ResourceModel\Recurring\ListRecurringDetails`) has `recurring` inside the `$_requiredFields` array, but looking at your [docs](https://docs.adyen.com/developers/api-reference/recurring-api#recurringdetailsrequest) `recurring` is not required.

**Comment by rikterbeek** [comment]
Hi @j3j5,

It is indeed not required anymore but if you want the contracts to be returned then you need to provide it. I think your purpose of doing the ListRecurringDetails is to retrieve the cards or not ?
I will check internally what the benefits is of doing the call without providing the contract to determine if we need to remove this from being a required field.

Regards,
Rik
Adyen

**Comment by j3j5** [comment]
I'm just saying it shouldn't be mandatory, although indeed, allowed to be submitted in case it's needed.

**Comment by rikterbeek** [comment]
Hi @j3j5,

Fixed in the above change. It is now possible to retrieve ONECLICK and RECURRING cards in one call.

Regards,
Rik
Adyen
