### ISSUE TITLE
[Checkout API] Cancel without the PSP reference endpoint

### ISSUE THREAD

**Issue by SVillette** [Adyen/adyen-php-api-library#406]
## Description

From the [doc](https://docs.adyen.com/online-payments/cancel?tab=codeBlockcancels_standalone_request_f1bV9_Java_2#cancel-without-psp), it is possible to cancel an authorized payment without a PSP reference.

From the namespace `Adyen\Service\ResourceModel\Checkout`, I found `Cancels` and `OrdersCancel` models that hit  `/payments/{paymentPspReference}/cancels` and `/orders/cancel` endpoints.

This would be useful as Java SDK has two methods in checkout service to cancel a payment:
- `checkout.paymentsCancels(paymentPspReference, paymentCancelRequest);` for the endpoint `/payments/{paymentPspReference}/cancels`
- `checkout.cancels(standalonePaymentCancelRequest);` for the endpoint `/cancels`

**Comment by peterojo** [comment]
Hi @SVillette! 
Thanks for the suggestion, we will consider adding technical cancels to the library.
If you are able to contribute a pull request we will highly appreciate it :)
