### ISSUE TITLE
Drop-in integration 000 Service checkoutSessions.php not present

### ISSUE THREAD

**Issue by makeitjump** [Adyen/adyen-php-api-library#414]
While trying to create a Drop-In Session I'm getting a response code 400 with the following message:

000 Service checkoutSessions.php not present

 while sending the following data:

Array
(
[amount] => Array
(
[currency] => EUR
[value] => 1245
)

[countryCode] => DE
[merchantAccount] => merchant
[reference] => 163
[returnUrl] => https://myreturnurl
[shopperLocale] => de_DE
[shopperEmail] => myEmail
[shopperReference] => 1
)

Is this a code or account problem?

Kind regards

Matthias

**Comment by jillingk** [comment]
Hi @makeitjump,

Thanks for reaching out to us with your issue. On first glance it seems that the service class that you're referring to seems to be wrong. Could you maybe supply some more information about your current integration, perhaps a code snippet of your class, so I can have a better idea of where the bug/fault lies? 

Best, Jilling
Adyen

**Comment by makeitjump** [comment]
Hi, yes of course.

$client = new Client();
        $client->setApplicationName(self::MITJ_ADYEN_APPLICATION_NAME);
        $client->setEnvironment((defined("MITJ_ADYEN_OPERATION_MODE") ? MITJ_ADYEN_OPERATION_MODE : \Adyen\Environment::TEST));
        if (!defined('MITJ_ADYEN_API_KEY')) {
            throw new \Exception('ADYEN: API KEY missing');
        }
        if (!defined('MITJ_ADYEN_MERCHANT_ACCOUNT')) {
            throw new \Exception('ADYEN: MERCHANT ACCOUNT missing');
        }
        $client->setXApiKey(MITJ_ADYEN_API_KEY);
        $service = new Checkout($client);

        $params = array(
            'amount' => array(
                'currency' => "EUR",
                'value' => $amount
            ),
            'countryCode' => $delivery_country_code,
            'merchantAccount' => MITJ_ADYEN_MERCHANT_ACCOUNT,
            'reference' => MITJ_ADYEN_REFERENCE_PREFIX . $orderId,
            'returnUrl' => $returnUrl . "&reference=" . MITJ_ADYEN_REFERENCE_PREFIX . $orderId,
            'shopperLocale' => (defined('MITJ_ADYEN_LOCALE')?MITJ_ADYEN_LOCALE:'de_DE'),
            'shopperEmail' => $customersEmailAddress,
            'shopperReference' => $customerId,
        );

        try {
            return $service->sessions($params);
        }
        catch(\Exception $e) {
            error_log($e->getMessage());
            error_log($e->getTraceAsString());
            return null;
        }

**Comment by makeitjump** [comment]
While setting the endpoint in 

/vendor/Adyen/Service/ResourceModel/Checkout/Sessions.php

to

https://checkout-test.adyen.com/v69/sessions

it works.

**Comment by jillingk** [comment]
Hi @makeitjump,

Glad to hear you got it to work. I just tested it for myself and your integration worked for me. The only thing that I had to do is add ```require __DIR__ . '/vendor/autoload.php';```, not sure if you also already had that somewhere in your script. Perhaps that fixes it for you?

Best, Jilling
Adyen
