### ISSUE TITLE
Session REQUEST fails with 404

### ISSUE THREAD

**Issue by makeitjump** [Adyen/adyen-php-api-library#415]
While switching to the live system, I get an error while trying to get the live sessions.

https://myprefix-checkout-live.adyenpayments.com/checkoutSessions.php/v69/sessions

delivers a 404 page on your side using this library.

If I try to call this page in the browser, it delivers a 404 as well.

Kind regards

Matthias

**Comment by jillingk** [comment]
Hi @makeitjump,

Thanks for reaching out again. I'm not quite sure what you're trying to do with the link here though. If you want to setup sessions for live, you make a post to [https://checkout-test.adyen.com/v69/sessions](https://checkout-test.adyen.com/v69/sessions) where you set test in the link to live. 

Also the sessions in this library should work for live as it does for test, so I don't think it's something library sided really. Perhaps if you have problems with your integration you can reach out to our technical support team, they should be able to assist you with any integration problems.

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @makeitjump,

Discard my previous comment, it seems that I was wrong on the live integration part. I will quickly look into it and then come back to you!

Best, Jilling
Adyen

**Comment by makeitjump** [comment]
Hey, 
thanks, it looks like an account problem. I've opened a support ticket as well.
I just wanted to make sure that it's not a problem with the library.

Kind regards

Matthias

**Comment by jillingk** [comment]
Hi @makeitjump,

All good, let me know how it works out with support. 

If there is anything else library related, you can let me know!

Kind regards, Jilling
Adyen

**Comment by makeitjump** [comment]
Hi, 
I spoke to the support.
The library is building the URL wrong.

The format of the URL in the live environment should be:
 
https://[random]-[company name]-checkout-live.adyenpayments.com/checkout/[version]/[method]
 
You can refer to this documentation for more info: https://docs.adyen.com/development-resources/live-endpoints#checkout-endpoints

this is how it should be.

What a actually get is: 
https://[random]-[company name]-checkout-live.adyenpayments.com/checkoutSessions.php/v69/sessions

So this sessions.php part needs to be removed in the library. 
It seems there are other endpoints affected as well.

Kind regards

Matthias

**Comment by jillingk** [comment]
Hi @makeitjump,

I just tested it on the latest library and it actually gives me precisely what it should be.. That is the library for me builds a url like ```https://PREFIX-checkout-live.adyenpayments.com/checkout/v69/sessions```. I'm not really sure why you don't get it that way. Which library and php version you are using?

The code I used is this;
```php
$client = new Adyen\Client();
$client->setApplicationName('Live Application');
$client->setEnvironment(\Adyen\Environment::LIVE, 'PREFIX');
$client->setTimeout(30);
$client->setXApiKey("APIKEY");
$service = new Checkout($client);
$result = $service->sessions($params);
```

Let me know if this somehow fixes it for you.

Best, Jilling
Adyen
