### ISSUE TITLE
Remove all references to Hosted Payment Pages (hpp)

### ISSUE THREAD

**Issue by tomfotherby** [Adyen/adyen-php-api-library#416]
This Adyen blog post: [Hosted payment pages deprecation: Out with the old, in with the new](https://www.adyen.com/blog/HPP-end-of-life)
says:

>  :warning:  From Oct 2022 we'll stop accepting payments through Hosted Payment Pages (HPP).

I noticed that [src/Adyen/Client.php](https://github.com/Adyen/adyen-php-api-library/blob/f09e0cf403e2b76a2e1de5b2118ddcd9d2b1cbb8/src/Adyen/Client.php) includes:

```
const ENDPOINT_LIVE_DIRECTORY_LOOKUP = "https://live.adyen.com/hpp/directory/v2.shtml";
```

It is my understanding that this endpoint is no longer available?

I propose the DIRECTORY lookup functionality that uses HPP is removed from this library in future versions to avoid confusion.

**Comment by jillingk** [comment]
Hi @tomfotherby,

Thanks for reaching out to us with this issue. You're right that we are indeed no longer supporting the HPP endpoints. Thanks for reminding us to delete these constants from the library, I will put a reminder for us to do so! If there is anything else we can help you with, please do let us know!

Best, Jilling
Adyen
