### ISSUE TITLE
Code examples use card object incorrectly. 

### ISSUE THREAD

**Issue by lofructose** [Adyen/adyen-php-api-library#418]
**Is your feature request related to a problem? Please describe.**
The example code in the readme uses the `card` object for encrypted card details, which is expected to throw an error. 

```Structure of card contains the following unknown fields: [encryptedCardNumber, encryptedSecurityCode, encryptedExpiryYear, encryptedExpiryMonth```

**Describe the solution you'd like**
Instead of the `card` object, the `paymentMethod` object would avoid the error -- like so: 

```
"paymentMethod": {
"type": "scheme",
"encryptedCardNumber": "test_4111111111111111",
"encryptedExpiryMonth": "test_03",
"encryptedExpiryYear": "test_2030",
"encryptedSecurityCode": "test_737"
},
```

**Additional context**
Docs for paymentMethod: https://docs.adyen.com/api-explorer/Checkout/69/post/payments#request-paymentMethod

**Comment by jillingk** [comment]
Hi @lofructose,

Thanks a lot for bringing this issue to our attention. I guess with all the changes to the checkout API we completely forgot to update the README :)

I will update this right now!

Best, Jilling
Adyen
