### ISSUE TITLE
Different exceptions for different errors

### ISSUE THREAD

**Issue by BackEndTea** [Adyen/adyen-php-api-library#425]
**Is your feature request related to a problem? Please describe.**
Right now if i want to catch a specific error from adyen, (in order to provide a better UX), i need to catch the general `AdyenException`, and then check against the message if it is one of the errors i can handle.

**Describe the solution you'd like**
Instead, if i this lib would throw a `CVCLenghtException`, (which extends from the `AdyenException`, as to preserve BC), i could catch that specifically, and don't have to worry about parsing a message, and then rethrowing the exception if its not the one i can handle.

**Describe alternatives you've considered**
The alternative is the current work around of checking against the message.

**Additional context**
Old vs new code:

```php
//old
try {
  $this->doAdyenThing();
} catch(AdyenException $e) {
  if($e->getMessage() === 'CVC Not right length.') {
    return 'something';
  }
  throw $e
}

//new
try {
  $this->doAdyenThing();
} catch(CVCLenghtException) {
  return 'something';
}
```

**Comment by jillingk** [comment]
Hey @BackEndTea,

Thanks a lot for reaching out to us with this issue. I see where you are getting from, however for us the main problem with this is the amount of API specific errors we would have to implement. As we're automating the libraries though, we could keep this in mind and see if this would be feasible to implement in the future.

Best, Jilling
Adyen
