### ISSUE TITLE
[PW-6912]Force the expiry of a payment link

### ISSUE THREAD

**Issue by deoomen** [Adyen/adyen-php-api-library#426]
**Is your feature request related to a problem? Please describe.**
Didn't find any method to force expiry of a payment link.

**Describe the solution you'd like**
`$requestOptions` in `paymentLinks` method in `Checkout` class should add option to change HTTP method.

**Describe alternatives you've considered**
IDK, any other option, another method or some other argument.

**Additional context**
`Checkout` class has only one method `paymentLinks` which has hardcoded sent only by `POST` HTTP method.

**Comment by jillingk** [comment]
Hi @deoomen,

Thanks a lot for reaching out to us with this issue. I see that we indeed have it still hardcoded to a post method request. I created an internal ticket for this and we're gonna take a look at it asap!

Best, Jilling
Adyen
