### ISSUE TITLE
POS terminal methods

### ISSUE THREAD

**Issue by VictorMetzler** [Adyen/adyen-php-api-library#429]
Hi guys, I do not know if this is the right spot do write but I've a question. Where do I find in this API the methods do talk with POS Terminals ? the only thing that I've found was this method ( getConnectedTerminals ). How do I, for example, send a payment to a terminal ?

I'm integreting my company with Adyen and my intent is to use 100% of your's API calls, but every step I take I discover that maybe it has not enough methods to suport everything, I really like to think otherwise because I prefere to use your methods than to make post/put/get calls directly to Adyens api.

If some one could help me I will be pleased.

**Comment by gjghendriks** [comment]
You can use the functions `runTenderAsync` or `runTenderSync`. But I think this underlies a bigger problem: there is no API explorer for the Cloudbased terminal API. Also the link in the readme of this project is broken.

**Comment by jillingk** [comment]
Hi @VictorMetzler,

Apologies for the delayed answer! @gjghendriks is completely right, you can use our Cloud based terminal solution by calling the ```runTenderAsync``` and ```runTenderSync``` functions to send payment requests to your POS terminal.  As of yet the php library unfortunately does not support the local terminal integration though. The naming is also a bit obsolete by now and in the other libraries we use a more descriptive naming, so we will be sure to change this is the future. 

I must say that this library is indeed not fully up to speed with our API's, however we are working very hard to make this completely one on one through an automation process! We have done this for our Node and Java Library and currently are in the process for the .Net library. When that is done, this library is next on the chopping block so hopefully you will see a lot of improvement here rather soon!

In the meantime, @VictorMetzler, is there any other functionalities right now that you are missing? If so I'll try to see if I can allocate some manpower to fix this in a bit of a shorter timeline.

@gjghendriks you're also spot on with the API explorer for the terminal integration, this is something we would really want to see (and which benefits our automation process as well). Luckily this is coming very soon in the next year as well!

Happy holidays!

Best, Jilling
Adyen

**Comment by VictorMetzler** [comment]
Please, any answer to the question above? it's been three weeks since the question . . .

**Comment by gjghendriks** [comment]
You would call it something like:

```
$adyen = (new Client())->getAdyenClient();
(new PosPayment($adyen))->runTenderAsync($request_body);
```

See https://docs.adyen.com/point-of-sale/basic-tapi-integration/make-a-payment on what to put in the request body

**Comment by VictorMetzler** [comment]
Thanks, but where do I identify which POS I'm sending? Could you describe the example a little better?
About the request_body, I assume it's the same that I already send for online payments.

**Comment by VictorMetzler** [comment]
Hi there, I can now send a payment to POS terminal payment, but some new things came out.

When I call the indicated method ( runTenderSync, not async, becouse I need the return of te call as indicated on https://docs.adyen.com/point-of-sale/basic-tapi-integration/make-a-payment#payment-response ), I get a timeout of your curl call, this happens every time I got a success call, all rejected calls is ok:

"Could not connect to Adyen (https://terminal-api-live.adyen.com/sync). Please check your internet connection and try again. (Network error [errno 28]: Operation timed out after 8001 milliseconds with 0 bytes received)"

Another thing, how can I indicate in JSON the properties of the payment ? where is it an Debit or Credit and the number os installmnets ?

My example:

{
  "SaleToPOIRequest": {
    "MessageHeader": {
      "ProtocolVersion": "3.0",
      "MessageClass": "Service",
      "MessageCategory": "Payment",
      "MessageType": "Request",
      "ServiceID": "U19T999P22",
      "SaleID": "0304232",
      "POIID": "V240mPlus-541926821"
    },
    "PaymentRequest": {
      "SaleData": {
        "SaleTransactionID": {
          "TransactionID": "PP|1|1|0",
          "TimeStamp": "2023-04-03T16:10:52+03:00"
        }
      },
      "PaymentTransaction": {
        "AmountsReq": {
          "Currency": "BRL",
          "RequestedAmount": 1
        }
      }
    }
  }
}
