### ISSUE TITLE
Fatal error: Class 'Adyen\TestCase' not found 

### ISSUE THREAD

**Issue by durgeshmandal** [Adyen/adyen-php-api-library#43]
I am trying to use php library but it giving me  error "Fatal error: Class 'Adyen\TestCase' not found" I have tried all version but giving same issue.
I had tried it with xampp and wamp server and also with with live server where I have SSL installed
Please help me to resolve issue 
I had tried to install library via composer to but is keep showing same

**Comment by lancergr** [comment]
Hi @durgeshmandal 

It seems as an autoloader issue since this class should be defined here:
https://github.com/Adyen/adyen-php-api-library/blob/develop/tests/TestCase.php

I would suggest to check that your composer install doesn't throw any errors and that you are including the composer autoloader.
If the issue persists, please share your full stacktrace.

Regards,
Giorgos
Adyen

**Comment by durgeshmandal** [comment]
Here is process and message after installation via composer 

C:\xampp\htdocs>composer require adyen/php-api-library
Using version ^1.4 for adyen/php-api-library
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing adyen/php-api-library (1.4.0): Loading from cache
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages
to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages
 to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an A
MQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a M
ongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log message
s to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages
to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log m
essages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log m
essages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages
to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages
to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to
 a Sentry server)
Writing lock file
Generating autoload files

**Comment by lancergr** [comment]
Hi @durgeshmandal 

Can you verify that you are including the composer autoloader and also share your stack trace with the error you reported?


Regards,
Giorgos
Adyen

**Comment by lancergr** [comment]
I am closing this. Feel free to re-open it if needed!

Regards,
Giorgos
Adyen
