### ISSUE TITLE
GET resources

### ISSUE THREAD

**Issue by rudiedirkx** [Adyen/adyen-php-api-library#431]
It seems the service classes only POST data to the API, but can't GET a resource.

I can do a `$checkout->paymentLinks($info);` to make a payment link, and remember its `id`, but how do I GET the payment link details: https://docs.adyen.com/api-explorer/Checkout/69/get/paymentLinks/_linkId_ with this package? Seems like something the checkout/paymentlinks service could do.

**Comment by jillingk** [comment]
Hi @rudiedirkx,

Thanks a lot for reaching out to us here, and massive apologies for the delayed answer. We have finally been able to add these new functionalities (in your case getPaymentlinks) to our library for checkout. Just a quick heads up :)

Best, Jilling
Adyen
