### ISSUE TITLE
Missing Google pay methods in ManualCapture

### ISSUE THREAD

**Issue by maaarghk** [Adyen/adyen-php-api-library#438]
Incorrect `false` result in `Adyen\Util\ManualCapture::isManualCaptureSupported` for `visa_googlepay` and `mc_googlepay` (possibly others)

Update: Visa and mc are there but these others appear in our account and not in this list:

```
        'amex_googlepay',
        'discover_googlepay',
        'maestro_googlepay',
```

(unless they don't support manual capture but I don't believe that is the case)

**Comment by maaarghk** [comment]
@wboereboom  pls :(

**Comment by jillingk** [comment]
@maaarghk,

My bad! I got that all the variants were added by now. I'll take a look into it right now.

Best, Jilling
Adyen

**Comment by maaarghk** [comment]
@jillingk I notice this file was updated in #458 but the other google pay variants are still not added

**Comment by maaarghk** [comment]
cc @carlosperales95

**Comment by carlosperales95** [comment]
https://github.com/Adyen/adyen-php-api-library/pull/499
