### ISSUE TITLE
Adyen - Unable to decrypt data

### ISSUE THREAD

**Issue by Ashok-AK** [Adyen/adyen-php-api-library#44]
Am facing an issue as "Unable to decrypt data" when i try to authorize the payment.

I have used CSE method and generated the encrypted form data. 

I have referred documentation from below url and send encrypted form value in card.encrypted.json. But am not sure what i am doing wrong. I have updated the username and password details from my WS user details. 

http://adyen.github.io/adyen-php-api-library/payment.html
{
  "amount": {
    "value": 1499,
    "currency": "GBP"
  },
  "reference": "payment-test",
  "merchantAccount": "MY_MERCHANT_ACCOUNT",
  "additionalData": {
    "card.encrypted.json": "MY_ENCRYPTION_DATA"
  }
}

**Comment by rikterbeek** [comment]
Hi @Ashok-AK,

If you get back "Unable to decrypt data" this means the data you provide in the call we can't decrypt. Probably this means you are using a different public key to decrypt the data then the public key that is present in the webserver that you are using in the API call. If you need more help with setting up the CSE script please contact our support at support@adyen.com.

Regards,
Rik
Adyen

**Comment by Dave-Nandwa** [comment]
@rikterbeek I'm currently facing this issue with the Web Drop-In Integration, been stuck for ages. Please help!

**Comment by miki-shalala** [comment]
> @rikterbeek I'm currently facing this issue with the Web Drop-In Integration, been stuck for ages. Please help!

Hello @Dave-Nandwa .
i was facing this, as @rikterbeek  mentioned, it means that the server is unable to decrypt using the provided keys

the mistake i was making is that i was using the public key from the ws@[my_account]
and for the /payment endpoint i was using the api-key from pos_certificate@[my_account]

causing the mismatch between them and rendering the service unable to decrypt
