### ISSUE TITLE
Missing / in Checkout endpoint

### ISSUE THREAD

**Issue by gromez** [Adyen/adyen-php-api-library#461]
It seems there's a bug in `AbstractResource` class. 
`checkoutEndpoint` is initialized twice: 
 - https://github.com/Adyen/adyen-php-api-library/blob/75bb15b789c02f0cf831233eb1194d41dd09101a/src/Adyen/Service/AbstractResource.php#L58-L59
 - https://github.com/Adyen/adyen-php-api-library/blob/75bb15b789c02f0cf831233eb1194d41dd09101a/src/Adyen/Service/AbstractResource.php#L62-L63

The last one does not have slash separator between endpoint and version, so it generates invalid URL. 
It should only affects `PaymentLinks` and `Recurring` because other resources do not use `checkoutEndpoint`. 

Possible to push a hotfix for this issue?

Thanks

**Comment by jillingk** [comment]
Closing issue as this has been fixed now. Thanks for notifying us with this issue @gromez
