### ISSUE TITLE
composer require adyen/php-api-library pulling a different version of code than the specified version in the doc

### ISSUE THREAD

**Issue by kkhs2** [Adyen/adyen-php-api-library#511]
I'm trying to implement a manual capture and the Adyen support team recommended me to use the following PHP class in order to facilitate this:

https://github.com/Adyen/adyen-php-api-library/blob/41a1bf2da795e0a447b7e703a6e2d75a2b22be5b/src/Adyen/Service/Checkout/ModificationsApi.php

According to the Github page the ModificationsApi.php file is located in adyen-php-api-library/src/Adyen/Service/Checkout, but from doing a composer require adyen/php-api-library as suggested in the README.md, I do not see such file or such directory.

The adyen PHP library version in my codebase is 14.0.1 after running composer require adyen/php-api-library, it looks as though that this is possibly pulling another version of the library which is a different version to the one specified in https://github.com/Adyen/adyen-php-api-library/

**Expected behavior**
When doing a composer require adyen/php-api-library, the expected behaviour is pulling the same directories and files as per the library here: https://github.com/Adyen/adyen-php-api-library

**Comment by wboereboom** [comment]
Hi @kkhs2 ,

Thank you for raising this issue.
The file you are trying to access was introduced at our v15 beta release. 
We are currently working on getting this version to go live.
It is taking us somewhat longer as we are introducing models, which is a very big change from how the library worked in the past.

Feel free to experiment with the beta, however. We are very much open to any comments or feedback you might have.

I hope this clears up the confusion. I understand we could have documented this better, for which I apologise.

Kind Regards,
Wouter
Adyen

**Comment by kkhs2** [comment]
Hello Wouter,

No worries at all. Thank you for taking a look.

Can I ask - if I was to use 14.0.1 version of the library and do a manual
capture, what is the best way to achieve this? Is there a similar method
(like setReference() as per the Java example in the doc) that I can use to
set the pspReference in the POST request URL?

Many thanks,
Kenneth

**Comment by jillingk** [comment]
Hi @kkhs2,

You can use [this class](https://github.com/Adyen/adyen-php-api-library/blob/14.0.1/src/Adyen/Service/Checkout.php) to achieve the same thing basically. Since we only used model based request/responses since the new beta version you have to work with arrays though. You can check the [API-explorer](https://docs.adyen.com/api-explorer/Checkout/latest/overview) to see which parameters you can submit in your array to a given endpoint. 

Let us know if you run into anything else!

Best, Jilling
Adyen
