### ISSUE TITLE
Merge develop into master to release https://github.com/Adyen/adyen-php-api-library/pull/50

### ISSUE THREAD

**Issue by billysmithers** [Adyen/adyen-php-api-library#53]
**Description**
- Could you please create a release so the pull request _Added a method to set the directory lookup URL. #50_ can be used as a version bump. Without this the package is not usable with a white label (self hosted) Adyen implementation (e.g. Barclaycard Smart Pay in the UK) as the directory lookup is hardcoded to point to adyen.com.

**Comment by rikterbeek** [comment]
Hi @billysmithers,

Yes we will do a new release today. Let you know when this is done.

Regards,
Rik
Adyen

**Comment by billysmithers** [comment]
Thanks Rik

**Comment by rikterbeek** [comment]
Hi @billysmithers,

Release is done: https://github.com/Adyen/adyen-php-api-library/releases/tag/1.4.1

Regards,
Rik
Adyen

**Comment by billysmithers** [comment]
Great thanks again Rik
