### ISSUE TITLE
CheckoutStateDataValidator removes origin parameter?

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-php-api-library#536]
**Describe the bug**
isn't the `origin` parameter provided by the components in the state data necesary for the api calls? evne if not, it is a provided correct parameter, so shouldn't the state data validator NOT Remove those?

**Comment by AndreasA** [comment]
might be related to https://github.com/Adyen/adyen-shopware6/issues/404 (or why it is done that way in that issue).

**Comment by wboereboom** [comment]
Hi @AndreasA ,

Thanks for raising this issue, and apologies for the belated response.

The stateDateValidatoer is marked as deprecated, and will be removed in a future major release.
Therefore we don't recommend its use any longer.

Kind Regards,
Wouter
Adyen

**Comment by AndreasA** [comment]
ok. then it should probably not be used anymore by your Shopware 6 plugin?

**Comment by AndreasA** [comment]
created a corresponding issue for Shopwate 6 https://github.com/Adyen/adyen-shopware6/issues/424 and with that I close this issue.
