### ISSUE TITLE
Fatal error on "Disable stored payment details" API call

### ISSUE THREAD

**Issue by anton-close** [Adyen/adyen-php-api-library#568]
**Describe the bug**
`\Adyen\Service\Checkout\RecurringApi::deleteTokenForStoredPaymentDetails()` gives fatal error "Adyen\Service::requestHttp(): Return value must be of type array, null returned". 

The problem is that this method `$this->requestHttp($endpoint, strtolower('DELETE'), null, $requestOptions);` must return array, but in fact NULL is returned. Adyen API 
`curl -X DELETE 'https://checkout-test.adyen.com/v70/storedPaymentMethods/{RECURRING_DETAIL_REFERENCE}?merchantAccount={YOUR_MERCHANT_ACCOUNT}&shopperReference={YOUR_SHOPPER_REFERENCE}' --header 'X-API-Key: YOUR_API_KEY'`
returns 204 with empty response, but Adyen Service always expects array. 

**To Reproduce**
1. Adyen PHP SDK version is 15.3.0.
2. Just call \Adyen\Service\Checkout\RecurringApi::deleteTokenForStoredPaymentDetails() method with required arguments

**Expected behavior**
No fatal error should happen.

**Comment by jillingk** [comment]
Hey @anton-close,

Thanks a lot for reaching out to us with this issue! We flagged this issue already actually have since fixed it in the latest release of v15.4.0! Let us know if you experience any other issues during your integration.

Best, Jilling
Adyen
