### ISSUE TITLE
Replacement for deprecated RiskManagement service

### ISSUE THREAD

**Issue by Genjiff** [Adyen/adyen-php-api-library#570]
Version 15 of this library deprecated `src/Adyen/Service/RiskManagement.php`, but unlike the other deprecated classes in the same version, there's no mention about what should be used instead in the file, documentation, PR, or commit message. Could you please document what should be used instead? Thank you!

**Comment by michaelpaul** [comment]
Hello @Genjiff, thanks for raising this issue. Indeed, we don't have a proper replacement for this service yet so we can keep its support. Abraços!
