### ISSUE TITLE
RecurringApi::deleteTokenForStoredPaymentDetails call fails even though the request is correctly performed and successfully finished

### ISSUE THREAD

**Issue by vasilake-v** [Adyen/adyen-php-api-library#579]
**Describe the bug**
Call to `\Adyen\Service\Checkout\RecurringApi::deleteTokenForStoredPaymentDetails` fails with `TypeError: Return value must be of type array, string returned`, although the request is finished successful

[Delete payment method](https://docs.adyen.com/api-explorer/Checkout/70/delete/storedPaymentMethods/_storedPaymentMethodId_) returns empty response with 204 code. That means, the same empty result is returned by `Adyen\HttpClient\CurlClient::requestHttp()` (empty string or null depending on `outputType` in config). 

Because `Adyen\Service::requestHttp()` directly returns result of previously mentioned method, it fails because `Adyen\Service::requestHttp(): array` (has a strict return type `array`)

**To Reproduce**
1. Perform a call to `\Adyen\Service\Checkout\RecurringApi::deleteTokenForStoredPaymentDetails` with usual arguments

**Expected behavior**
Either return empty array, success result dto, or at least no error :)

**Additional context**
Currently we are at package version: `v15.4.0`. Although there is a newer version the package, the [`requestHttp()`](https://github.com/Adyen/adyen-php-api-library/blob/b80e4f1b271676c6bc33572d9685b1d4644391a1/src/Adyen/HttpClient/CurlClient.php#L259)  method is similar

**Comment by michaelpaul** [comment]
Hello @vasilake-v, thanks for reporting this issue! A fix shall be released soon on our next major.

**Comment by vasilake-v** [comment]
@michaelpaul thanks for taking care about this. Do you think we could replicate/have similar fix for previous major version ? 
So we also allow other package users (still using lower version) to benefit from functionality, while still following their own timetable for smooth migration plan from Arrays -> DTOs ( instead of rushing and repriotize other things for upgrading to the new major version, only for this fix)

I can port [the fix](https://github.com/Adyen/adyen-php-api-library/pull/581) on the `v15` and prepare a pull request

**Comment by vasilake-v** [comment]
@michaelpaul Thank you! :+1:
