### ISSUE TITLE
Error using splitCardFundingSources in paymentMethods

### ISSUE THREAD

**Issue by pgrimaud** [Adyen/adyen-php-api-library#593]
Hello,

We have an issue while using the parameter `splitCardFundingSources` in the https://checkout-test.adyen.com/v71/paymentMethods endpoint. We're also using the last v16 SDK.

Here's our code :

```php
new PaymentMethodsRequest([
    'splitCardFundingSources' => true,
    // with other parameters
]);
```

The issue : 

<img width="604" alt="image" src="https://github.com/Adyen/adyen-php-api-library/assets/1866496/023bffee-6794-47e2-8b05-b4894f7f62b7">

This exception is throw by [this method](https://github.com/Adyen/adyen-php-api-library/blob/main/src/Adyen/Model/Checkout/PaymentMethod.php#L454) which use [this other method.](https://github.com/Adyen/adyen-php-api-library/blob/main/src/Adyen/Model/Checkout/PaymentMethod.php#L273)

This error occurred due to this enum in the OpenAPI schema : https://github.com/Adyen/adyen-openapi/blob/main/json/CheckoutService-v71.json#L9919 and the endpoint return paymentMethod as with `credit` and `debit` cards.

Could you take a look at it?

Thanks

**Comment by jillingk** [comment]
Hi @pgrimaud,

Thanks for reaching out here with this issue. We're looking into it.

Best, Jilling
Adyen

**Comment by pgrimaud** [comment]
Any update?

**Comment by jillingk** [comment]
Hi @pgrimaud,

Our apologies for the wait. We had some other things on our plate but finally got around to fixing it, this fix should be released next week! 

Best, Jilling 
Adyen
