### ISSUE TITLE
countryCode is required for a DirectoryRequest

### ISSUE THREAD

**Issue by WesleyE** [Adyen/adyen-php-api-library#6]
The manual states:

"All the fields mentioned in the request example (currencyCode, merchantAccount, paymentAmount, skinCode, merchantReference, sessionValidity and merchantSig), except countryCode, are mandatory."

However, the countryCode in the directoryRequest is set to mandatory. I've fixed it for now by giving it a value of 0, but it would be lovely to just supply the request with the right parameters.

**Comment by rikterbeek** [comment]
Hi Wesly,

It is recommended that you provide the countryCode field, to accurately state the actual location of the payment, so that the correct payment methods for that location are retrieved. That is why it is mandatory in the library.  Why do you not want to supply it ?

Regards,
Rik
Adyen

**Comment by WesleyE** [comment]
Hi Rick,

Thanks for your quick reply. This is because the users might have set a different shipping location than the country they are originally from. We do want to supply the locale to have the payment options translated, but not want to disable for example iDeal for users who are from The Netherlands but want to have their products delivered in Germany.

Regards, Wesley

**Comment by rikterbeek** [comment]
Hi Wesley,

Could you not better use the country that is selected in the Billing Address ? If you do not send us a countryCode we give back payment methods based on the IP address of your server. I will remove this validation check because it is not mandatory but I still advise you to use it.

Regards,
Rik
Adyen
