### ISSUE TITLE
 Requesting session API returns failure ( version 17.0.0)

### ISSUE THREAD

**Issue by huangxy7** [Adyen/adyen-php-api-library#609]
Requesting session API returns failure
document：https://docs.adyen.com/online-payments/build-your-integration/?platform=Web&integration=Hosted+Checkout
calss: \Adyen\Service\Checkout\PaymentsApi::class
method: sessions
params: 
    {   
    "amount":{
            "value":9800,
            "currency":"HKD"
        },
        "merchantAccount":"****",
        "returnUrl":"https://*****",
        "mode":"hosted",
        "themeId":"1f71***",
        "reference":"****",
        "countryCode":"HK",
        "expiresAt":"2024-01-17T08:56:24+00:00",
        "shopperReference":"****",
        "shopperStatement":"***",
        "enableRecurring":true,
 }
response:
    errormsg :"The field 'threeDSAuthenticationOnly' is not supported when mode: 'hosted'."

**Comment by DjoykeAbyah** [comment]
Hi @[huangxy7](https://github.com/huangxy7),

Thank you for reaching out to us, and apologies for the delayed reply!

By default, the ThreeDSauthenticationOnly boolean is unintentionally set to false. We have removed it in v17.1.1. I've verified this to be certain, so updating to v17.1.1 would resolve this issue.

Kind regards,

Djoyke
Adyen
