### ISSUE TITLE
Correction code

### ISSUE THREAD

**Issue by jowebNET** [Adyen/adyen-php-api-library#61]
**PHP version**: > 5.6.0
**Library version**: @Latest
**Description**

$client = new \Adyen\Client();
$client->setApplicationName("Adyen PHP Api Library Example");
$client->setUsername("YOUR USERNAME");
$client->setPassword("YOUR PASSWORD");
$client->setEnvironment(\Adyen\Environment::TEST);
//Add  namespace to \Adyen\
$service = new  \Adyen\Service\Payment($client);

$json = '{
      "card": {
        "number": "4111111111111111",
        "expiryMonth": "6",
        "expiryYear": "2016",
        "cvc": "737",
        "holderName": "John Smith"
      },
      "amount": {
        "value": 1500,
        "currency": "EUR"
      },
      "reference": "payment-test",
      "merchantAccount": "YOUR MERCHANT ACCOUNT"
}';

$params = json_decode($json, true);

$result = $service->authorise($params);

**Comment by rikterbeek** [comment]
Hi @jowebNET,

What is your question ?

Regards,
Rik
Adyen

**Comment by jowebNET** [comment]
Ok think you
