### ISSUE TITLE
Market Pay Account/Fund ?

### ISSUE THREAD

**Issue by danielsum** [Adyen/adyen-php-api-library#64]
Hi there, 

If I'm right, the package didn't manage the Market Pay Account/Fund services ? 

Is it planned or should I extend the package on my own ? 

Thanks in advance !

**Comment by lancergr** [comment]
Hi @danielsum 

Indeed, the MarketPay endpoints are not yet included on the library. Feel welcome to extend the library and submit a Pull Request!

Let me know in case you are interested on extending it. Basically, the MarketPay API Account, Fund and Notification services 
https://docs.adyen.com/api-explorer/#/Account/v4/overview
https://docs.adyen.com/api-explorer/#/Fund/v3/overview
https://docs.adyen.com/api-explorer/#/NotificationConfigurationService/v1/overview
should be implemented similarly to Payment service
https://github.com/Adyen/adyen-php-api-library/blob/develop/src/Adyen/Service/Payment.php

Kind Regards,
Giorgos
Adyen

**Comment by danielsum** [comment]
Hi Giorgos, 

Finally, it seems that I cannot have an access to your Fund Api for my project (visibly we need to be first in production mode before to test your solution ?). So we are forced to switch to Lemonway or MangoPay unfortunately... Too bad, I wanted to extend your PHP SDK for Fund Services and also make a Laravel Package for the Php community that could work as the Cashier plugin for Stripe/Braintree :/

But thanks for your quick reply !

Dan

**Comment by rikterbeek** [comment]
Hi @danielsum,

Nol, you can test it into our test environment but you need to have the MarketPay role. It could be that the merchant was not able to comply with our rules to use the MarketPay solution. If you have any questions around this please contact us at support@adyen.com. If you have any technical questions around implementation for the future you can always create a new issue, I will close this one for now.

Regards,
Rik
Adyen
