### ISSUE TITLE
Wrong parameter type in metadata functions

### ISSUE THREAD

**Issue by GunniBusch** [Adyen/adyen-php-api-library#652]
In this function, the parameter type also includes null. but it should not be null.

Could there be just no action if it is null? 

```php
    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Metadata consists of entries, each of which includes a key and a value. Limits: * Maximum 20 key-value pairs per request. * Maximum 20 characters per key. * Maximum 80 characters per value.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
```

PS: it is in all `setMetadata` functions.

**Comment by jillingk** [comment]
Hi @GunniBusch,

We've just merged a fix that removes the null check. We realised that the serialiser will omit these during serialisation anyways so we simply use null values to remove fields on the setter. This means null is allowed as means to remove pre-filled fields. Hope that makes sense and answers your question.

Best, Jilling
Adyen
