### ISSUE TITLE
Can you make this library not suck?

### ISSUE THREAD

**Issue by fortytwofortyone** [Adyen/adyen-php-api-library#661]
**Is your feature request related to a problem? Please describe.**
Yes, parameterize all functions so you don't have to guess what should be in $params. Make the code actually readable instead of this type of loose sand. This does not simplify using Adyen over any framework HTTPClient. Actually use your head when you design these libraries. 

For instance here is an example.  

`public function getConnectedTerminals($params) //pure shit, don't know what to pass, have to look for obfuscated API docs online where 5 pages describe the terminal API but only one of those tells you which parameters you need. `

`public function getConnectedTerminals(string $merchant, string $store = '', string $terminalId = '') )  // clear and error proof interface that does not suck.`

Automation / libraries should make things easier, not just the same level of hard in a different way. You should be ashamed.

**Comment by jillingk** [comment]
Hi @fortytwofortyone,

Thanks for reaching out here and I'm very sorry to hear you experience with this library has been suboptimal. Do note that this is a bit of and older part of the library (one that we have not automated yet) which meant it's a bit simpler implementation-wise to say the least. We will do our best to revise it anytime soon! In the meantime please let us know if you run into anything else.

Best, Jilling
Adyen
