### ISSUE TITLE
Non-nullable billingToken issue for non-recurring PayPal payments

### ISSUE THREAD

**Issue by emnsen** [Adyen/adyen-php-api-library#664]
Hi all,

**Describe the bug**
My issue is related to [PaymentCompletionDetails.php#L539](https://github.com/Adyen/adyen-php-api-library/blob/main/src/Adyen/Model/Checkout/PaymentCompletionDetails.php#L539). I don't have anything to do with recurring payment and even in the [documentation](https://docs.adyen.com/api-explorer/Checkout/71/post/payments/details#request-details-billingToken) it says It's for the recurring payment, but the code doesn't allow me to continue my process.

**Screenshots**
This is the payload that I got.
![Payload](https://github.com/Adyen/adyen-php-api-library/assets/5148536/d1f8b4cc-af63-4622-9314-9e06029024c4)

**Expected behavior**
Billing token should be nullable

**Comment by jillingk** [comment]
Hey @emnsen,

Thanks for reaching out here. What library version are you on? I remember we fixed this issue with nullables in the past at some point. 

Best, Jilling
Adyen

**Comment by emnsen** [comment]
Hey @jillingk 

I'm using [v18.1.0](https://github.com/Adyen/adyen-php-api-library/blob/v18.1.0/src/Adyen/Model/Checkout/PaymentCompletionDetails.php#L539).

**Comment by jillingk** [comment]
@emnsen,

Ah my bad I see this is a string field, the fix I was thinking about was for bools. 

Thanks for the contribution, however these models are auto generated based on templates and hence we should modify it there. I'll make sure we will do this asap.

Best, Jilling
Adyen

**Comment by emnsen** [comment]
Hey @jillingk 
Would it be possible to share any timeline for when this fix will happen?

**Comment by jillingk** [comment]
Hi @emnsen,

Very sorry for the slow response! I've just opened a PR to fix your issue. We should have this released this week :)

Best, Jilling
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @emnsen! 

I just wanted to quickly update you that the fix has been released!

Regards,

Djoyke
Adyen
