### ISSUE TITLE
Util/Util::calculateSha256Signature not valid for HMAC Notification signatures?

### ISSUE THREAD

**Issue by Mark-H** [Adyen/adyen-php-api-library#72]
**PHP version**: 7.2.1
**Library version**: 1.5.0
**Description**

I'm trying to verify the HMAC signature provided by [notifications](https://docs.adyen.com/developers/notifications/signing-notifications-with-hmac), and thought I could use the util included in this library for that. 

But it looks like that's not valid for notifications, as it uses a different signature format?

In particular, to get the right signature to be calculated, I needed to change these lines:

        // Sort the array by key using SORT_STRING order
        ksort($params, SORT_STRING);

        // Generate the signing data string
        $signData = implode(":", array_map($escapeval, array_merge(array_keys($params), array_values($params))));

To the following to (1) avoid it from messing up the order; in the calling code I'm constructing $params in the field order as defined in the documentation and (2) to not include the parameter key names into the $signData.

        // Sort the array by key using SORT_STRING order
        // Remove: ksort($params, SORT_STRING);

        // Generate the signing data string
        $signData = implode(":", array_map($escapeval, array_values($params)));

Is it expected that this utility can't be used for notifications or is this a bug?

**Comment by rikterbeek** [comment]
Hi @Mark-H,

The util is build in a way to use it for signing the HPP data for the request.
For notifications this process is indeed different. You do not have to sort it and you only provide it with the values not the keys. What we could do is build another method called something like calculateSha256SignatureForNotifications that is doing your code. If you want to add this into the library we are allowing PR for it if you include it with some test cases.

Regards,
Rik
Adyen

**Comment by Aleffio** [comment]
Hmac calculation for notifications is now available in the latest 3.1.0 version:
https://github.com/Adyen/adyen-php-api-library/pull/117/files

closing the issue,

Kind Regards,
Alessio
Adyen
