### ISSUE TITLE
Package update but no version released

### ISSUE THREAD

**Issue by joshlopes** [Adyen/adyen-php-api-library#89]
We started getting an error on our tests because some public methods have been renamed from client on an update 8 days ago but no version was released for that changes, this is a BC break. We were hoping these changes would be in a 1.5.4, but instead the commit hash for 1.5.3 changed to a different one.

Do you follow semver?

Change: https://github.com/Adyen/adyen-php-api-library/commit/5d8cad34e860fead324c97af1c9553e12847a21e#diff-abc460192ba028e993913c78030f5e15L231

Problem in screen shots:

![image](https://user-images.githubusercontent.com/3440849/49082747-78029a80-f242-11e8-9e57-f9b7f7185a24.png)

![image](https://user-images.githubusercontent.com/3440849/49082780-8bae0100-f242-11e8-8e2c-0531736d411c.png)

**Comment by rikterbeek** [comment]
Hi @joshlopes,

Sorry for the inconvenience we had made a mistake with the release of 1.5.3 as this contained the same data as 1.5.2. We decided to re-release 1.5.3 so the data was correct according this version. We just released 1.5.4 so best to move over to this version.

Regards,
Rik
Adyen

**Comment by joshlopes** [comment]
Thank you @rikterbeek, can you please also let me know if adyen follows semantic versioning (semver) https://semver.org/ ?

**Comment by rikterbeek** [comment]
Hi @joshlopes @oradwell,

Yes we are following this. We will not make this mistake again.

Regards,
Rik
Adyen
