### ISSUE TITLE
replace dependency monolog/monolog to Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by Grummfy** [Adyen/adyen-php-api-library#9]
Hello,
to let people deal with they logger, you should replace monolog with the psr logger interface. This allow an independent implementation and avoid potential conflict

**Comment by rikterbeek** [comment]
Hi @Grummfy,

You can use your own logger by setting the setLogger() method on the client. It expects a Psr logger interface. We want to create a default monolog logger if this is not provided to make it easier for our merchant to integrate.

Regards,
Rik
Adyen

**Comment by Grummfy** [comment]
yes, but it's an useless dependency. But OK.

**Comment by rikterbeek** [comment]
Hi @Grummfy,

I understand that this is for you a useless dependency because you are using a different logger, but we need to add this dependency because on default it is using the monolog for logging and if you do not have it it will cause issues.

Regards,
Rik
Adyen
