### ISSUE TITLE
Adyen\AdyenException: Not allowed?!

### ISSUE THREAD

**Issue by oxodesign** [Adyen/adyen-php-api-library#95]
**PHP version**: 7.2
**Library version**: 1.5.4
**Description**
Im running the example code and getting `Adyen\AdyenException: Not allowed`. 

Under transactions dashboard I can see that the transaction is there with the status "Rejected".

Can anyone help me in this case?! Or is this by design?!

Thank you

**Comment by rikterbeek** [comment]
HI @oxodesign,

You don't have the permission on Adyen side. It looks like you do not use the right credentials or you are trying to hit an API where you do not have permission for. Check your credentials and if that is not solving your issue contact support@adyen.com.

Regards,
Rik
Adyen
