### ISSUE TITLE
Uncaught Error: Class 'PHPUnit_Framework_TestCase' not foun

### ISSUE THREAD

**Issue by stefanneke** [Adyen/adyen-php-api-library#98]
**PHP version**: 7.3.1
**Library version**: 1.6
**Description**

Running the testcase.php (from autoload) gives me this error.
i installed phpunit v 7 from composer.
Any thoughs?

**Comment by Naktibalda** [comment]
@stefanneke You need PhpUnit 4 to get tests working.

**Comment by cyattilakiss** [comment]
Hi,

@stefanneke Yes indeed, running these tests require PHPUnit v4. (I use v 4.8)
@Naktibalda Thank you for the answer

Best,
Attila
Adyen
